import { supabase } from './supabase'
import { sha256Hex } from './sha256'
import type { FieldDef, ListResult, Measurement, MetaStatus, OptionList, OptionValue, Sample, VaultFile } from './types'

type WritePayload = { columns: Record<string, unknown>; meta: Record<string, unknown>; meta_status: Record<string, MetaStatus> }
type ListParams = { q?: string; filters?: Record<string, unknown>; sort?: { key: string; desc: boolean }; limit?: number; offset?: number; defs?: FieldDef[] }
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const fail = (error: { message: string } | null) => { if (error) throw new Error(error.message) }
const column = (key: string, defs: FieldDef[]) => defs.find((def) => def.key === key)?.column_name
// Kept separately from list functions so the filter rules remain identical for samples and measurements.
function filterQuery(query: { eq: (a:string,b:unknown)=>typeof query; in: (a:string,b:unknown[])=>typeof query; gte:(a:string,b:string|number)=>typeof query; lte:(a:string,b:string|number)=>typeof query; contains:(a:string,b:Record<string,unknown>)=>typeof query }, filters: Record<string, unknown>, defs: FieldDef[]) {
  let next = query
  for (const [key, value] of Object.entries(filters)) {
    if (value === '' || value === undefined || (Array.isArray(value) && !value.length)) continue
    const name = column(key, defs); const target = name ?? `meta->>${key}`
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      const range = value as { min?: unknown; max?: unknown; from?: unknown; to?: unknown }
      if (range.min !== undefined) next = next.gte(target, name ? range.min as string|number : String(range.min))
      if (range.max !== undefined) next = next.lte(target, name ? range.max as string|number : String(range.max))
      if (range.from !== undefined) next = next.gte(target, name ? range.from as string|number : String(range.from))
      if (range.to !== undefined) next = next.lte(target, name ? range.to as string|number : String(range.to))
    } else if (name) next = Array.isArray(value) ? next.in(name, value) : next.eq(name, value)
    else next = next.contains('meta', { [key]: value })
  }
  return next
}
async function userEmail() { const { data, error } = await supabase.auth.getUser(); fail(error); return data.user?.email ?? null }
export async function listSamples(params: ListParams = {}): Promise<ListResult<Sample>> { const defs=params.defs??[]; let query=supabase.from('samples').select('*',{count:'exact'}); if(params.q) query=query.or(`sample_id.ilike.%${params.q}%,label.ilike.%${params.q}%`); query=filterQuery(query as unknown as Parameters<typeof filterQuery>[0],params.filters??{},defs) as unknown as typeof query; const key=params.sort?.key; query=query.order(key ? (column(key,defs) ?? `meta->>${key}`) : 'updated_at',{ascending:!params.sort?.desc,nullsFirst:false}).range(params.offset??0,(params.offset??0)+(params.limit??50)-1); const {data,error,count}=await query; fail(error); return {items:(data??[]) as Sample[],total:count??0} }
export async function getSample(idOrSampleId: string): Promise<Sample|null> { const {data,error}=await supabase.from('samples').select('*')[uuid.test(idOrSampleId)?'eq':'eq'](uuid.test(idOrSampleId)?'id':'sample_id',idOrSampleId).maybeSingle(); fail(error); return data as Sample|null }
export async function createSample(payload: WritePayload): Promise<Sample> { const {data,error}=await supabase.from('samples').insert({...payload.columns,meta:payload.meta,meta_status:payload.meta_status,created_by:await userEmail()}).select('*').single(); fail(error); return data as Sample }
export async function updateSample(id:string,payload:Partial<WritePayload>,expectedUpdatedAt?:string):Promise<Sample>{ const current=await getSample(id); if(!current) throw new Error('sample not found'); if(expectedUpdatedAt&&current.updated_at!==expectedUpdatedAt) throw new Error('conflict: sample changed since you opened it'); const {data,error}=await supabase.from('samples').update({...payload.columns,meta:{...current.meta,...(payload.meta??{})},meta_status:{...current.meta_status,...(payload.meta_status??{})}}).eq('id',id).select('*').single(); fail(error); return data as Sample }
export async function deleteSample(id:string):Promise<void>{ const {error}=await supabase.from('samples').delete().eq('id',id); fail(error) }
export async function listMeasurements(sampleUuid:string,params:ListParams={}):Promise<ListResult<Measurement>>{ const defs=params.defs??[]; let query=supabase.from('measurements').select('*',{count:'exact'}).eq('sample_id',sampleUuid); query=filterQuery(query as unknown as Parameters<typeof filterQuery>[0],params.filters??{},defs) as unknown as typeof query; const key=params.sort?.key??'measured_on'; query=query.order(column(key,defs)??(key==='measured_on'?'measured_on':`meta->>${key}`),{ascending:params.sort ? !params.sort.desc : false,nullsFirst:false}).range(params.offset??0,(params.offset??0)+(params.limit??50)-1); const {data,error,count}=await query; fail(error); return {items:(data??[]) as Measurement[],total:count??0} }
export async function getMeasurement(id:string):Promise<Measurement|null>{ const {data,error}=await supabase.from('measurements').select('*').eq('id',id).maybeSingle(); fail(error); return data as Measurement|null }
export async function createMeasurement(sampleUuid:string,payload:WritePayload):Promise<Measurement>{ const {data,error}=await supabase.from('measurements').insert({...payload.columns,sample_id:sampleUuid,meta:payload.meta,meta_status:payload.meta_status,created_by:await userEmail()}).select('*').single(); fail(error); return data as Measurement }
export async function updateMeasurement(id:string,payload:Partial<WritePayload>,expectedUpdatedAt?:string):Promise<Measurement>{ const current=await getMeasurement(id); if(!current) throw new Error('measurement not found'); if(expectedUpdatedAt&&current.updated_at!==expectedUpdatedAt) throw new Error('conflict: measurement changed since you opened it'); const {data,error}=await supabase.from('measurements').update({...payload.columns,meta:{...current.meta,...(payload.meta??{})},meta_status:{...current.meta_status,...(payload.meta_status??{})}}).eq('id',id).select('*').single(); fail(error); return data as Measurement }
export async function deleteMeasurement(id:string):Promise<void>{ const {error}=await supabase.from('measurements').delete().eq('id',id); fail(error) }
export async function listFiles(measurementId:string):Promise<VaultFile[]>{ const {data,error}=await supabase.from('files').select('*').eq('measurement_id',measurementId).order('created_at'); fail(error); return (data??[]) as VaultFile[] }
export function kindFromName(name:string){ const ext=name.split('.').pop()?.toLowerCase(); return ext==='xls'||ext==='xlsx'?'raw_xls':['csv','tsv','txt'].includes(ext??'')?'raw_csv':['png','jpg','jpeg','svg'].includes(ext??'')?'plot_png':'other' }
export function parseFilenameClient(name:string){ const run=name.match(/Run(\d+)/i)?.[1]; const date=name.match(/(\d{2})-(\d{2})-(\d{4})/) ; const lower=name.toLowerCase(); return {run_number:run?Number(run):null,file_date:date?`${date[3]}-${date[1]}-${date[2]}`:null,detected_kind:/dc[- ]?iv|dciv/.test(lower)?'dciv':/ac[- ]?iv|aciv|hysteresis/.test(lower)?'aciv':/pund/.test(lower)?'pund':/\bcv\b/.test(lower)?'cv':null} }
const cleanName=(name:string)=>name.replace(/[^\p{L}\p{N} ._\-@#()]/gu,'_').slice(0,180)
export async function uploadFile(measurement:Measurement,sample:Sample,file:File,onProgress?:(pct:number)=>void):Promise<VaultFile>{ const sha256=await sha256Hex(file); const {data:dupe,error:dupeError}=await supabase.from('files').select('id').eq('measurement_id',measurement.id).eq('sha256',sha256).maybeSingle(); fail(dupeError); if(dupe) throw new Error('duplicate: this file is already attached'); const base=`samples/${sample.sample_id}/${measurement.id}/${cleanName(file.name)}`; let path=base; for(let n=1;n<=5;n++){ const suffix=n===1?'':`-${n}`; path=n===1?base:base.replace(/(\.[^.]*)?$/,`${suffix}$1`); const {error}=await supabase.storage.from('vault').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'}); if(!error) break; if(n===5||!(error.message.includes('already exists')||error.statusCode==='409')) throw new Error(error.message) } onProgress?.(100); const {data,error}=await supabase.from('files').insert({measurement_id:measurement.id,storage_path:path,original_name:file.name,kind:kindFromName(file.name),size_bytes:file.size,sha256,parsed:parseFilenameClient(file.name),upload_state:'ready',created_by:await userEmail()}).select('*').single(); fail(error); return data as VaultFile }
export async function getFileUrl(file:VaultFile,expiresSec=300):Promise<string>{ const {data,error}=await supabase.storage.from('vault').createSignedUrl(file.storage_path,expiresSec); fail(error); if(!data) throw new Error('Unable to create signed URL'); return data.signedUrl }
export async function deleteFile(file:VaultFile):Promise<void>{ const {error}=await supabase.storage.from('vault').remove([file.storage_path]); fail(error); const result=await supabase.from('files').delete().eq('id',file.id); fail(result.error) }
export async function getFieldDefs(entity:FieldDef['entity'],includeInactive=false):Promise<FieldDef[]>{ let q=supabase.from('field_definitions').select('*').eq('entity',entity).order('sort_order'); if(!includeInactive) q=q.eq('active',true); const {data,error}=await q; fail(error); return (data??[]) as FieldDef[] }
export async function upsertFieldDef(def:Partial<FieldDef>&Pick<FieldDef,'entity'|'key'>):Promise<FieldDef>{ const q=def.id?supabase.from('field_definitions').update(def).eq('id',def.id):supabase.from('field_definitions').insert(def); const {data,error}=await q.select('*').single(); fail(error); return data as FieldDef }
export async function getOptionLists(includeInactive=false):Promise<OptionList[]>{ const q=supabase.from('option_lists').select('*, values:option_values(*)').order('key'); const {data,error}=await q; fail(error); return ((data??[]) as OptionList[]).map((item)=>({...item,values:includeInactive?item.values:item.values.filter((value)=>value.active)})) }
export async function upsertOptionValue(v:Partial<OptionValue>&Pick<OptionValue,'list_key'|'value'>):Promise<OptionValue>{ const q=v.id?supabase.from('option_values').update(v).eq('id',v.id):supabase.from('option_values').insert(v); const {data,error}=await q.select('*').single(); fail(error); return data as OptionValue }
export async function getStats(){ const [samples,measurements,files,kindRows,sizeRows,recentRows]=await Promise.all([supabase.from('samples').select('*',{count:'exact',head:true}),supabase.from('measurements').select('*',{count:'exact',head:true}),supabase.from('files').select('*',{count:'exact',head:true}),supabase.from('measurements').select('kind'),supabase.from('files').select('size_bytes'),supabase.from('measurements').select('id,sample_id,measured_on,kind,samples(sample_id)').order('measured_on',{ascending:false}).limit(10)]); [samples,measurements,files,kindRows,sizeRows,recentRows].forEach((r)=>fail(r.error)); const by_kind:Record<string,number>={}; for(const row of (kindRows.data??[]) as {kind:string|null}[]) if(row.kind) by_kind[row.kind]=(by_kind[row.kind]??0)+1; const bytes=((sizeRows.data??[]) as {size_bytes:number|null}[]).reduce((sum,row)=>sum+(row.size_bytes??0),0); const recent=((recentRows.data??[]) as unknown as Array<Pick<Measurement,'id'|'sample_id'|'measured_on'|'kind'>&{samples:{sample_id:string}|null}>).map(({samples:sample,sample_id:sample_uuid,...row})=>({...row,measurement_id:row.id,sample_id:sample?.sample_id ?? '',sample_uuid,sample_key:sample?.sample_id ?? ''})); return {samples:samples.count??0,measurements:measurements.count??0,files:files.count??0,bytes,by_kind,recent} }
