import { sha256Hex } from './sha256'
import type { FieldDef, ListResult, Measurement, MetaStatus, OptionList, OptionValue, Sample, VaultFile } from './types'

type WritePayload = { columns: Record<string, unknown>; meta: Record<string, unknown>; meta_status: Record<string, MetaStatus> }
type ListParams = { q?: string; filters?: Record<string, unknown>; sort?: { key: string; desc: boolean }; limit?: number; offset?: number; defs?: FieldDef[] }
type Stats = { samples:number; measurements:number; files:number; bytes:number; by_kind:Record<string,number>; recent:Array<{id:string;measurement_id:string;sample_id:string;sample_uuid?:string;sample_key?:string;measured_on:string|null;kind:string|null}> }
type ApiError = Error & { code?: string; details?: unknown }
const apiBase=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'')
async function fail(response:Response){if(response.ok)return response;const body=await response.json().catch(()=>null) as {error?:{code?:string;message?:string;details?:unknown}}|null;throw Object.assign(new Error(body?.error?.message??`Request failed (${response.status})`),{code:body?.error?.code??'request_failed',details:body?.error?.details}) as ApiError}
async function request<T>(path:string,init:RequestInit={},relative=false):Promise<T>{const response=await fetch(`${apiBase}${relative?'':'/api'}${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...init.headers},...init});await fail(response);return response.status===204?undefined as T:response.json() as Promise<T>}
const column=(key:string,defs:FieldDef[])=>defs.find((def)=>def.key===key)?.column_name
function listQuery(params:ListParams){const query=new URLSearchParams();if(params.q)query.set('q',params.q);if(params.sort){query.set('sort',column(params.sort.key,params.defs??[])??params.sort.key);query.set('order',params.sort.desc?'desc':'asc')}if(params.limit!==undefined)query.set('limit',String(params.limit));if(params.offset!==undefined)query.set('offset',String(params.offset));for(const [key,value] of Object.entries(params.filters??{})){if(value===''||value===undefined||(Array.isArray(value)&&!value.length))continue;const target=column(key,params.defs??[])??`meta.${key}`;if(Array.isArray(value))for(const item of value)query.append(target,String(item));else if(typeof value==='object'&&value!==null)for(const [bound,item] of Object.entries(value))if(item!==undefined&&item!=='')query.set(`${target}.${bound}`,String(item));else query.set(target,String(value))}const result=query.toString();return result?`?${result}`:''}
async function userEmail(){const {principal}=await request<{principal:{actor?:string}}>('/me');return principal?.actor??null}
export async function listSamples(params:ListParams={}):Promise<ListResult<Sample>>{return request<ListResult<Sample>>(`/samples${listQuery(params)}`)}
export async function getSample(idOrSampleId:string):Promise<Sample|null>{try{return (await request<{sample:Sample}>(`/samples/${encodeURIComponent(idOrSampleId)}`)).sample}catch(error){if((error as ApiError).code==='not_found')return null;throw error}}
export async function createSample(payload:WritePayload):Promise<Sample>{return (await request<{sample:Sample}>('/samples',{method:'POST',body:JSON.stringify({...payload.columns,meta:payload.meta,meta_status:payload.meta_status,created_by:await userEmail()})})).sample}
export async function updateSample(id:string,payload:Partial<WritePayload>,expectedUpdatedAt?:string):Promise<Sample>{return (await request<{sample:Sample}>(`/samples/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({...payload.columns,meta:payload.meta,meta_status:payload.meta_status,expected_updated_at:expectedUpdatedAt})})).sample}
export async function deleteSample(id:string):Promise<void>{await request(`/samples/${encodeURIComponent(id)}`,{method:'DELETE'})}
export async function listMeasurements(sampleUuid:string,params:ListParams={}):Promise<ListResult<Measurement>>{return request<ListResult<Measurement>>(`/samples/${encodeURIComponent(sampleUuid)}/measurements${listQuery(params)}`)}
export async function getMeasurement(id:string):Promise<Measurement|null>{try{return (await request<{measurement:Measurement}>(`/measurements/${encodeURIComponent(id)}`)).measurement}catch(error){if((error as ApiError).code==='not_found')return null;throw error}}
export async function createMeasurement(sampleUuid:string,payload:WritePayload):Promise<Measurement>{return (await request<{measurement:Measurement}>(`/samples/${encodeURIComponent(sampleUuid)}/measurements`,{method:'POST',body:JSON.stringify({...payload.columns,meta:payload.meta,meta_status:payload.meta_status,created_by:await userEmail()})})).measurement}
export async function updateMeasurement(id:string,payload:Partial<WritePayload>,expectedUpdatedAt?:string):Promise<Measurement>{return (await request<{measurement:Measurement}>(`/measurements/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({...payload.columns,meta:payload.meta,meta_status:payload.meta_status,expected_updated_at:expectedUpdatedAt})})).measurement}
export async function deleteMeasurement(id:string):Promise<void>{await request(`/measurements/${encodeURIComponent(id)}`,{method:'DELETE'})}
export async function listFiles(measurementId:string):Promise<VaultFile[]>{return (await request<{items:VaultFile[]}>(`/measurements/${encodeURIComponent(measurementId)}/files`)).items}
export async function listFilesForSample(sampleUuid:string):Promise<VaultFile[]>{return (await request<{items:VaultFile[]}>(`/samples/${encodeURIComponent(sampleUuid)}/files`)).items}
export async function uploadFile(measurement:Measurement,sample:Sample,file:File,onProgress?:(pct:number)=>void):Promise<VaultFile>{void sample;const sha256=await sha256Hex(file);const upload=await request<{file_id:string;storage_path:string;upload_url:string;method:string}>('/files/upload-url',{method:'POST',body:JSON.stringify({measurement_id:measurement.id,filename:file.name,size_bytes:file.size,sha256})});const result=await request<{file:VaultFile}>(upload.upload_url,{method:upload.method,headers:{'Content-Type':file.type||'application/octet-stream'},body:file},true);onProgress?.(100);return result.file}
// Kept async so the call sites (which await it, and cache it through react-query) are
// untouched, but there is no request any more: the Access session cookie authorises
// <img src> and <a href> directly, so there is nothing to sign and nothing to expire.
export async function getFileUrl(file:VaultFile):Promise<string>{return `${apiBase}/api/files/${encodeURIComponent(file.id)}/content`}
export async function deleteFile(file:VaultFile):Promise<void>{await request(`/files/${encodeURIComponent(file.id)}`,{method:'DELETE'})}
export async function getFieldDefs(entity:FieldDef['entity'],includeInactive=false):Promise<FieldDef[]>{return (await request<{items:FieldDef[]}>(`/field-definitions?entity=${encodeURIComponent(entity)}${includeInactive?'&include_inactive=1':''}`)).items}
export async function upsertFieldDef(def:Partial<FieldDef>&Pick<FieldDef,'entity'|'key'>):Promise<FieldDef>{return (await request<{field_definition:FieldDef}>(def.id?`/field-definitions/${encodeURIComponent(def.id)}`:'/field-definitions',{method:def.id?'PATCH':'POST',body:JSON.stringify(def)})).field_definition}
export async function getOptionLists(includeInactive=false):Promise<OptionList[]>{return (await request<{items:OptionList[]}>(`/option-lists${includeInactive?'?include_inactive=1':''}`)).items}
export async function upsertOptionValue(v:Partial<OptionValue>&Pick<OptionValue,'list_key'|'value'>):Promise<OptionValue>{const path=v.id?`/option-values/${encodeURIComponent(v.id)}`:`/option-lists/${encodeURIComponent(v.list_key)}/values`;return (await request<{option_value:OptionValue}>(path,{method:v.id?'PATCH':'POST',body:JSON.stringify(v)})).option_value}
export async function getStats():Promise<Stats>{return request<Stats>('/stats')}
