import crypto from 'node:crypto';

const cacheTtlMs = 10 * 60 * 1000;
let keyCache = null;

function decodePart(part, name) { if (!/^[A-Za-z0-9_-]+$/.test(part)) throw new Error(`invalid JWT ${name}`); try { return JSON.parse(Buffer.from(part, 'base64url').toString('utf8')); } catch { throw new Error(`invalid JWT ${name}`); } }
async function getKeys(refresh = false) { if (!refresh && keyCache && keyCache.expiresAt > Date.now()) return keyCache.keys; const teamUrl = process.env.VAULT_ACCESS_TEAM_URL; if (!teamUrl) throw new Error('VAULT_ACCESS_TEAM_URL is not set'); const response = await fetch(`${teamUrl}/cdn-cgi/access/certs`); if (!response.ok) throw new Error('failed to fetch Access signing keys'); const body = await response.json(); if (!Array.isArray(body.keys)) throw new Error('invalid Access signing keys'); keyCache = { keys: body.keys, expiresAt: Date.now() + cacheTtlMs }; return keyCache.keys; }
async function getKey(kid) { let keys = await getKeys(); let key = keys.find((candidate) => candidate.kid === kid); if (key) return key; keys = await getKeys(true); key = keys.find((candidate) => candidate.kid === kid); if (!key) throw new Error('unknown JWT signing key'); return key; }

export async function verifyAccessJwt(token) { if (typeof token !== 'string') throw new Error('invalid JWT'); const parts = token.split('.'); if (parts.length !== 3) throw new Error('invalid JWT'); const header = decodePart(parts[0], 'header'); const payload = decodePart(parts[1], 'payload'); if (!header || typeof header !== 'object' || typeof header.kid !== 'string' || header.alg !== 'RS256') throw new Error('invalid JWT header'); const key = await getKey(header.kid); if (key.kty !== 'RSA' || key.alg !== 'RS256' || typeof key.n !== 'string' || typeof key.e !== 'string') throw new Error('invalid JWT signing key'); if (!/^[A-Za-z0-9_-]+$/.test(parts[2])) throw new Error('invalid JWT signature'); let publicKey; try { publicKey = crypto.createPublicKey({ key: { kty: 'RSA', n: key.n, e: key.e }, format: 'jwk' }); } catch { throw new Error('invalid JWT signing key'); } if (!crypto.verify('RSA-SHA256', Buffer.from(`${parts[0]}.${parts[1]}`), publicKey, Buffer.from(parts[2], 'base64url'))) throw new Error('invalid JWT signature'); const now = Math.floor(Date.now() / 1000); const skew = 60; const audience = process.env.VAULT_ACCESS_AUD; if (!audience || !(typeof payload.aud === 'string' ? [payload.aud] : Array.isArray(payload.aud) ? payload.aud : []).includes(audience)) throw new Error('invalid JWT audience'); if (typeof payload.exp !== 'number' || !Number.isFinite(payload.exp) || payload.exp < now - skew) throw new Error('expired JWT'); if (typeof payload.iat !== 'number' || !Number.isFinite(payload.iat) || payload.iat > now + skew) throw new Error('invalid JWT issued-at time'); return payload; }
