import { supabaseAdmin } from './supabaseAdmin.js'; import { ApiError } from './respond.js'; import { requireDate } from './validate.js';
const cache = { defs: new Map(), lists: new Map(), loadedAt: 0 }; const TTL = 60000; const roles = ['substrate', 'bottom_metal', 'il_bot', 'fe', 'il_top', 'top_metal', 'other'];
async function refresh() { if (Date.now() - cache.loadedAt < TTL && cache.loadedAt) return; const sb = supabaseAdmin(); const [d, l] = await Promise.all([sb.from('field_definitions').select('*').order('sort_order'), sb.from('option_values').select('*').order('sort_order')]); if (d.error) throw d.error; if (l.error) throw l.error; cache.defs = new Map(); for (const x of d.data) { const a = cache.defs.get(x.entity) || []; a.push(x); cache.defs.set(x.entity, a); } cache.lists = new Map(); for (const x of l.data) { const a = cache.lists.get(x.list_key) || []; a.push(x); cache.lists.set(x.list_key, a); } cache.loadedAt = Date.now(); }
export async function loadDefs(entity, { includeInactive = false } = {}) { await refresh(); return (cache.defs.get(entity) || []).filter((x) => includeInactive || x.active); }
export async function loadLists({ includeInactive = false } = {}) { await refresh(); return new Map([...cache.lists].map(([k, v]) => [k, v.filter((x) => includeInactive || x.active)])); }
export function bustCache() { cache.loadedAt = 0; }
export function __setCacheForTests(defs = {}, lists = {}) { cache.defs = new Map(Object.entries(defs)); cache.lists = new Map(Object.entries(lists)); cache.loadedAt = Date.now(); }
function invalid(key, message, errors) { errors.push({ key, message }); }
function coerce(def, value, errors) { if (value === '') return null; const type = def.type; if (value == null) return null; if (['text', 'longtext', 'select', 'person'].includes(type)) { if (typeof value !== 'string') invalid(def.key, 'must be a string', errors); return value; } if (type === 'number' || type === 'integer') { const n = typeof value === 'number' ? value : (typeof value === 'string' && value.trim() ? Number(value) : NaN); if (!Number.isFinite(n) || (type === 'integer' && !Number.isInteger(n))) invalid(def.key, `must be ${type === 'integer' ? 'an integer' : 'a number'}`, errors); return n; } if (type === 'date') { try { return requireDate(value, def.key); } catch { invalid(def.key, 'must be YYYY-MM-DD', errors); return value; } } if (type === 'bool') { if (value === true || value === false) return value; if (value === 'true') return true; if (value === 'false') return false; invalid(def.key, 'must be a boolean', errors); return value; } if (type === 'multiselect') { const v = typeof value === 'string' ? value.split(',').map((x) => x.trim()).filter(Boolean) : value; if (!Array.isArray(v) || v.some((x) => typeof x !== 'string')) invalid(def.key, 'must be an array of strings', errors); return v; } if (type === 'layer_stack') { if (!Array.isArray(value) || value.some((x) => !x || typeof x !== 'object' || !roles.includes(x.role) || typeof x.material !== 'string' || !Number.isFinite(x.t_nm) && x.t_nm !== null && x.t_nm !== undefined)) invalid(def.key, 'must be an array of valid stack layers', errors); return value; } return value; }
export async function validateEntity(entity, body, { partial = false, current = {} } = {}) { if (!body || typeof body !== 'object' || Array.isArray(body)) throw new ApiError(400, 'invalid_body', 'Request body must be a JSON object'); const defs = await loadDefs(entity); const lists = await loadLists({ includeInactive: true }); const byKey = new Map(defs.map((d) => [d.key, d])); const columns = {}, meta = {}, meta_status = {}, warnings = [], errors = []; const add = (def, value) => { const v = coerce(def, value, errors); if (v != null && typeof v === 'number' && ((def.min != null && v < def.min) || (def.max != null && v > def.max))) invalid(def.key, 'is outside allowed range', errors); if (v != null && def.regex && typeof v === 'string' && !(new RegExp(def.regex).test(v))) invalid(def.key, 'does not match required format', errors); if (v != null && def.options_list_key) { const vals = lists.get(def.options_list_key) || []; for (const opt of (Array.isArray(v) ? v : [v])) { const item = vals.find((x) => x.value === opt); const old = current[def.column_name || def.key] ?? current.meta?.[def.key]; if (!item || (!item.active && !(Array.isArray(old) ? old.includes(opt) : old === opt))) invalid(def.key, 'contains an invalid or inactive option', errors); } } (def.column_name ? columns : meta)[def.column_name || def.key] = v; };
 for (const [key, value] of Object.entries(body)) { if (key === 'expected_updated_at') columns.__expected_updated_at = value; else if (key === 'meta' && value && typeof value === 'object' && !Array.isArray(value)) for (const [k,v] of Object.entries(value)) { const d=byKey.get(k); if(d) add(d,v); else warnings.push(`unknown key "${k}" ignored`); } else if (key === 'meta_status' && value && typeof value === 'object' && !Array.isArray(value)) for (const [k,v] of Object.entries(value)) { if (byKey.has(k) && ['confirmed','assumed','unknown'].includes(v)) meta_status[k]=v; else invalid(k, 'meta_status must be confirmed, assumed, or unknown for a known field', errors); } else { const d=byKey.get(key); if(d) add(d,value); else warnings.push(`unknown key "${key}" ignored`); } }
 if (!partial) for (const d of defs) { const target = d.column_name ? columns : meta; const key = d.column_name || d.key; if (d.required && (!Object.prototype.hasOwnProperty.call(target, key) || target[key] == null)) invalid(d.key, 'required', errors); } if (errors.length) throw new ApiError(422, 'validation_failed', 'Validation failed', errors); return { columns, meta, meta_status, warnings }; }
export async function defsForSchema() { const all = {}; for (const e of ['sample','measurement','file']) all[e] = (await loadDefs(e)).sort((a,b) => a.sort_order-b.sort_order); return all; }
export async function listsForSchema() { const m = await loadLists(); return Object.fromEntries([...m].map(([k,v]) => [k, v.map(({value,label}) => ({value,label}))])); }
