import { defsForSchema, listsForSchema } from './fieldDefs.js';
const routes = [
  { method:'GET', path:'/api/samples', query:['q','family','substrate','fab_location','meta.<key>','sort','order','limit','offset'] }, { method:'POST', path:'/api/samples', body:['sample fields'] }, { method:'GET|PATCH|DELETE', path:'/api/samples/:id', query:['include'], body:['sample fields','expected_updated_at'] }, { method:'GET|POST', path:'/api/samples/:id/measurements', query:['kind','measured_by','from','to','sort','order','limit','offset'], body:['measurement fields'] }, { method:'GET|PATCH|DELETE', path:'/api/measurements/:id', query:['include'], body:['measurement fields','expected_updated_at'] }, { method:'GET', path:'/api/measurements/:id/files' }, { method:'POST', path:'/api/files/upload-url', body:['measurement_id','filename','size_bytes','sha256'] }, { method:'POST', path:'/api/files/:id/register', body:['size_bytes','sha256','parsed'] }, { method:'POST', path:'/api/files', body:['measurement_id','filename','content_base64'] }, { method:'GET', path:'/api/files/:id/download' }, { method:'DELETE', path:'/api/files/:id' }, { method:'GET|POST', path:'/api/field-definitions', query:['entity','include_inactive'], body:['field definition fields'] }, { method:'GET|PATCH|DELETE', path:'/api/field-definitions/:id', body:['field definition fields'] }, { method:'GET', path:'/api/option-lists' }, { method:'GET|POST', path:'/api/option-lists/:key/values', query:['include_inactive'], body:['value','label','sort_order','meta'] }, { method:'PATCH|DELETE', path:'/api/option-values/:id', body:['value','label','sort_order','meta'] }, { method:'GET', path:'/api/stats' },
  // Everything below arrived with the Part 2 features and was missing here until the whole set
  // was built. That silence was a real defect, not an omission of detail: the contract calls
  // this "the self-describing document an agent needs", cli/vault.py validates its flags against
  // it, and a route absent from it is a route a caller has no way to discover. A feature that is
  // not in /api/schema does not exist as far as an agent is concerned.
  { method:'GET', path:'/api/me' },
  { method:'GET', path:'/api/bench/duts' }, { method:'GET', path:'/api/bench/runs' }, { method:'GET', path:'/api/bench/runs/:runId' }, { method:'GET', path:'/api/bench/coverage', query:['dut_id','run_id'] }, { method:'GET', path:'/api/bench/cells', query:['dut_id','run_id','limit','offset'] }, { method:'GET', path:'/api/bench/analysis/cells' }, { method:'GET', path:'/api/bench/lines' }, { method:'GET', path:'/api/bench/captures/:captureId/content' },
  { method:'GET', path:'/api/review-queue', query:['status','entity','field','limit','offset'] }, { method:'POST', path:'/api/review-queue/:id/accept' }, { method:'POST', path:'/api/review-queue/:id/reject' },
  { method:'POST', path:'/api/uploads/analyze', body:['paths'] }, { method:'POST', path:'/api/uploads/commit', body:['sample_id','groups'] },
  { method:'GET', path:'/api/kinds', note:'measurement_kinds, units and column_units in one response. Units are per COLUMN, not per axis.' },
  { method:'GET|POST', path:'/api/figures', query:['q','sort','order','limit','offset'], body:['title','spec','description','slug','pinned_extractor_version'] }, { method:'GET|PATCH|DELETE', path:'/api/figures/:id', note:':id is a uuid or a slug; GET also returns `sources`, so a dangling trace reference is visible rather than drawn as a blank panel.' },
  { method:'GET', path:'/api/cohort-keys', note:'The migration-authored allow-lists for grouping and metrics. Read-only.' },
  { method:'GET|POST', path:'/api/cohorts', query:['q','sort','order','limit','offset'], body:['name','predicate','metric','group_by','description','slug','extractor_version'] }, { method:'GET|PATCH|DELETE', path:'/api/cohorts/:id' },
  { method:'POST', path:'/api/cohorts/summary', body:['predicate','metric','group_by','extractor_version','cohort_id'], note:'Every group returns n, an exclusion ledger that balances (n_members = n_with_metric + n_no_metric_row + n_refused), and the provenance of the GROUPING KEY. A cohort chart that omits any of the three is incomplete.' },
  { method:'GET|POST', path:'/api/devices', query:['sample_id','address_scheme','q','sort','order','limit','offset'], body:['sample_id','device_address','notes'], note:'POST creates a vault_label device only; grid coordinates come from device_tests, never from a request body.' },
  { method:'GET', path:'/api/devices/:id' }, { method:'GET', path:'/api/devices/:id/history', query:['from','to','event_kind','limit','offset'] },
  { method:'POST', path:'/api/devices/:id/aliases', body:['alias_address','alias_scheme','reason'], note:'Refused for a machine principal: an alias merges two device histories and must carry a real person behind it.' }, { method:'DELETE', path:'/api/devices/:id/aliases/:aliasId' },
  { method:'POST', path:'/api/devices/register-bench', body:['dut_id'] },
  { method:'GET', path:'/api/verdict-changes', query:['dut_id','direction','from','to','sort','order','limit','offset'] },
  { method:'POST', path:'/api/search/ask', body:['question'], note:'Returns a FILTER URL or a refusal. The agent reads the schema and never a measurement row.' }, { method:'POST', path:'/api/search/:id/accepted' }, { method:'GET', path:'/api/search/history', query:['q','refused','limit','offset'] }
];
export async function buildSchemaDoc() { const base={ name:'agni-data-vault', version:'2', conventions:{case:'snake_case',dates:'YYYY-MM-DD',auth:'Bearer VAULT_API_KEY (machine), or a verified Cf-Access-Jwt-Assertion (human)'},routes,upload_flow:['POST /api/files/upload-url','PUT bytes to the returned upload_url (relative, same Bearer auth)','GET /api/files/:id/content to verify'],query_surface:{note:'For direct SQL, pandas or an agent: read the flat views rather than meta JSONB. A field without a column_name lives in meta, where meta->>key is TEXT -- a numeric field sorts lexically (9 > 10) and a range filter compares strings. The flat views promote every active meta field to a correctly typed column, and are regenerated whenever a field definition changes.',views:['vault.samples_flat','vault.measurements_flat','vault.measurement_bench_run','vault.device_history','vault.device_verdict_changes','vault.figure_sources'],tables:['vault.measurement_metrics','vault.measurement_kinds','vault.units','vault.column_units','vault.devices','vault.cohorts','vault.metric_definitions','vault.cohort_group_keys'],bench:['public.campaign_runs','public.device_tests','public.device_coverage','public.captures','public.cell_analysis','public.run_analysis'],rest_base:'/rest/v1 on the tailnet origin, with a role=vault_read service JWT for read-only access'} }; try { const defs=await defsForSchema(); const entities=Object.fromEntries(Object.entries(defs).map(([k,v])=>[k,{fields:v}])); return {...base,entities,option_lists:await listsForSchema()}; } catch(error) { return {...base,entities:{},option_lists:{},warnings:[`field_definitions unavailable: ${error.message}`]}; } }
