export const BUCKET = 'vault';
const clean = (name) => String(name).replace(/[^A-Za-z0-9 ._@#()\-]/g, '_').slice(0, 180);
export function buildStoragePath(sampleId, measurementId, filename) { return `samples/${sampleId}/${measurementId}/${clean(filename)}`; }
// Validate rather than let an unset env var surface as "Cannot read properties of
// undefined". api/_lib/supabaseAdmin.js states the same requirement the same way.
const storageBase = () => { const url = process.env.VAULT_STORAGE_URL; if (!url) throw new Error('VAULT_STORAGE_URL environment variable must be set'); return url.replace(/\/$/, ''); };
const objectUrl = (path, bucket) => `${storageBase()}/storage/v1/object/${encodeURIComponent(bucket)}/${String(path).split('/').map(encodeURIComponent).join('/')}`;
const authHeaders = () => { const jwt = process.env.VAULT_SERVICE_JWT; if (!jwt) throw new Error('VAULT_SERVICE_JWT environment variable must be set'); return { Authorization: `Bearer ${jwt}` }; };
async function storageFetch(path, bucket, options) { const response = await fetch(objectUrl(path, bucket), { ...options, headers: { ...authHeaders(), ...options.headers } }); if (!response.ok) { const text = await response.text(); const err = new Error(`Storage request failed with HTTP ${response.status}: ${text}`); err.status = response.status; throw err; } return response; }
export async function putObject(path, body, contentType, bucket = 'vault') { const options = { method: 'POST', headers: { 'content-type': contentType, 'x-upsert': 'false' }, body }; if (!Buffer.isBuffer(body)) options.duplex = 'half'; const response = await storageFetch(path, bucket, options); return response.json(); }
export async function getObject(path, bucket = 'vault') { const response = await storageFetch(path, bucket, { method: 'GET', headers: {} }); const length = response.headers.get('content-length'); return { body: response.body, contentType: response.headers.get('content-type'), size: length === null ? null : Number(length) }; }
export async function headObject(path, bucket = 'vault') { const response = await fetch(objectUrl(path, bucket), { method: 'HEAD', headers: authHeaders() }); if (response.status === 404) return false; if (!response.ok) { const text = await response.text(); const err = new Error(`Storage request failed with HTTP ${response.status}: ${text}`); err.status = response.status; throw err; } return true; }
export async function deleteObject(path, bucket = 'vault') { if (bucket !== BUCKET) throw new Error(`Storage delete is forbidden for bucket ${bucket}`); await storageFetch(path, bucket, { method: 'DELETE', headers: {} }); }
export function parseFilename(name) { const s = String(name); const run = s.match(/Run(\d+)/i); const date = s.match(/(\d{2})-(\d{2})-(\d{4})/); const l = s.toLowerCase(); const detected_kind = /dc[- ]?iv|dciv|\bdc\b/.test(l) ? 'dciv' : /ac[- ]?iv|aciv|hysteresis|\bac\b/.test(l) ? 'aciv' : /pund/.test(l) ? 'pund' : /\bcv\b|c-v/.test(l) ? 'cv' : null; return { run_number: run ? Number(run[1]) : null, file_date: date ? `${date[3]}-${date[1]}-${date[2]}` : null, detected_kind }; }
export function kindFromExtension(name) { const ext = String(name).toLowerCase().match(/\.([^.]+)$/)?.[1]; if (['xls', 'xlsx'].includes(ext)) return 'raw_xls'; if (['csv', 'tsv', 'txt'].includes(ext)) return 'raw_csv'; if (['png', 'jpg', 'jpeg', 'svg'].includes(ext)) return 'plot_png'; return 'other'; }
