import { supabaseAdmin } from './supabaseAdmin.js'; export const BUCKET = 'vault';
const clean = (name) => String(name).replace(/[^A-Za-z0-9 ._@#()\-]/g, '_').slice(0, 180);
export function buildStoragePath(sampleId, measurementId, filename) { return `samples/${sampleId}/${measurementId}/${clean(filename)}`; }
export async function createSignedUploadUrl(path) { const { data, error } = await supabaseAdmin().storage.from(BUCKET).createSignedUploadUrl(path); if (error) throw error; return { signed_url: data.signedUrl, token: data.token, path }; }
export async function createSignedDownloadUrl(path, expiresSec = 300) { const { data, error } = await supabaseAdmin().storage.from(BUCKET).createSignedUrl(path, expiresSec); if (error) throw error; return data.signedUrl; }
export async function removeObject(path) { const { error } = await supabaseAdmin().storage.from(BUCKET).remove([path]); if (error) throw error; }
export async function uploadBase64(path, base64, contentType = 'application/octet-stream') { const { data, error } = await supabaseAdmin().storage.from(BUCKET).upload(path, Buffer.from(base64, 'base64'), { contentType, upsert: false }); if (error) throw error; return data; }
export function parseFilename(name) { const s = String(name); const run = s.match(/Run(\d+)/i); const date = s.match(/(\d{2})-(\d{2})-(\d{4})/); const l = s.toLowerCase(); const detected_kind = /dc[- ]?iv|dciv|\bdc\b/.test(l) ? 'dciv' : /ac[- ]?iv|aciv|hysteresis|\bac\b/.test(l) ? 'aciv' : /pund/.test(l) ? 'pund' : /\bcv\b|c-v/.test(l) ? 'cv' : null; return { run_number: run ? Number(run[1]) : null, file_date: date ? `${date[3]}-${date[1]}-${date[2]}` : null, detected_kind }; }
export function kindFromExtension(name) { const ext = String(name).toLowerCase().match(/\.([^.]+)$/)?.[1]; if (['xls', 'xlsx'].includes(ext)) return 'raw_xls'; if (['csv', 'tsv', 'txt'].includes(ext)) return 'raw_csv'; if (['png', 'jpg', 'jpeg', 'svg'].includes(ext)) return 'plot_png'; return 'other'; }
