import { ApiError } from './respond.js';
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const isUuid = (value) => typeof value === 'string' && UUID.test(value);
export function requireUuid(value, name = 'id') { if (!isUuid(value)) throw new ApiError(400, 'invalid_id', `${name} must be an RFC 4122 uuid`); return value; }
export function requireDate(value, name = 'date') { if (value == null || value === '') return null; if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new ApiError(422, 'invalid_date', `${name} must be YYYY-MM-DD or null`); const [year, month, day] = value.split('-').map(Number); const date = new Date(year, month - 1, day); if (date.getFullYear() !== year || date.getMonth() !== month - 1 || date.getDate() !== day) throw new ApiError(422, 'invalid_date', `${name} must be YYYY-MM-DD or null`); return value; }
export function requireString(value, name = 'value') { if (typeof value !== 'string' || !value.trim()) throw new ApiError(422, 'validation_failed', `${name} must be a non-empty string`); return value; }
export function pickAllowed(body, allowedKeys, warnings = []) { if (!body || typeof body !== 'object' || Array.isArray(body)) throw new ApiError(400, 'invalid_body', 'Request body must be a JSON object'); const picked = {}; for (const key of Object.keys(body)) { if (allowedKeys.includes(key)) picked[key] = body[key]; else warnings.push(`unknown key "${key}" ignored`); } return picked; }
export function parsePagination(query = {}) { const num = (v, d) => v == null || v === '' ? d : Number(v); let limit = num(query.limit, 50); let offset = num(query.offset, 0); if (!Number.isInteger(limit) || limit < 1) limit = 50; if (!Number.isInteger(offset) || offset < 0) offset = 0; return { limit: Math.min(limit, 200), offset }; }
export function parseSort(query = {}, allowedKeys = [], defs = []) { const key = query.sort; if (!key) return null; const def = defs.find((d) => d.key === key); if (!allowedKeys.includes(key) && !def) return null; return def && !def.column_name ? { metaKey: key, ascending: query.order !== 'desc', cast: def.type } : { column: def?.column_name || key, ascending: query.order !== 'desc', cast: def?.type }; }
