// @ts-nocheck
import { beforeEach, describe, expect, it, vi } from 'vitest';

const state = { samples: [], measurements: [], files: [], review_queue: [], inserts: [] };
vi.mock('../api/_lib/supabaseAdmin.js', () => ({ supabaseAdmin: () => ({ from(table) { const q = { table, filters: [], action: 'select', payload: null, select() { return this; }, eq(k, v) { this.filters.push([k, v]); return this; }, maybeSingle() { return this.run(true); }, single() { return this.run(true); }, insert(v) { this.action = 'insert'; this.payload = v; return this; }, async run(single) { const rows = state[table]; const hit = () => rows.filter((x) => this.filters.every(([k, v]) => x[k] === v)); if (this.action === 'select') { const data = hit(); return { data: single ? data[0] || null : data, error: null }; } const items = Array.isArray(this.payload) ? this.payload : [this.payload]; const made = items.map((item) => ({ id: `${table}-${rows.length + 1}`, ...item })); rows.push(...made); state.inserts.push([table, this.payload]); return { data: single ? made[0] : made, error: null }; }, then(ok, bad) { return this.run(false).then(ok, bad); } }; return q; } }) }));
vi.mock('../api/_lib/storage.js', () => ({ buildStoragePath: (s, m, f) => `samples/${s}/${m}/${f}`, kindFromExtension: () => 'raw_xls' }));
vi.mock('../api/_lib/evidence.js', () => ({ extractFromPath: (path) => ({ confirmed: path.includes('Run7') ? { run_numbers: { value: [7], class: 'E2', source: 'Run7 in filename' }, measured_on: { value: '2026-05-22', class: 'E2', source: '05-22-2026 in filename' } } : {} }), proposeGroups: (files) => [{ key: 'folder:7', folder: 'folder', run_number: 7, files: files.map((f) => f.path), confirmed: { run_numbers: { value: [7], class: 'E2', source: 'Run7 in filename' } }, queued: [] }] }));
vi.mock('../api/_lib/fieldDefs.js', () => ({ validateEntity: vi.fn(async (_entity, values) => ({ columns: { ...(values.run_numbers ? { run_numbers: values.run_numbers } : {}) }, meta: Object.fromEntries(Object.entries(values).filter(([k]) => k !== 'run_numbers' && k !== 'meta_status')), meta_status: values.meta_status ?? {}, warnings: [] })) }));
const api = await import('../api/_lib/resources/uploads.js');
const id = '11111111-1111-4111-8111-111111111111'; const hash = 'a'.repeat(64); const file = { path: 'folder/Run7 DC-IV 05-22-2026.xls', size_bytes: 12, sha256: hash }; const confirmed = { run_numbers: { value: [7], class: 'E2', source: 'Run7 in filename' } };
beforeEach(() => { state.samples = [{ id, sample_id: 'S-1' }]; state.measurements = []; state.files = []; state.review_queue = []; state.inserts = []; vi.clearAllMocks(); });
const err = async (fn) => { try { await fn(); } catch (error) { return error; } };
describe('uploads API resource', () => {
  it('analyzes without inserts', async () => { const result = await api.analyze({ files: [file] }); expect(result.body.groups).toHaveLength(1); expect(state.inserts).toEqual([]); });
  it('writes evidence and confirmed status with each confirmed value', async () => { await api.commit({ sample_id: id, groups: [{ key: 'folder:7', confirmed, queued: [], files: [file] }] }); const measurement = state.measurements[0]; expect(measurement.meta.evidence.run_numbers).toEqual({ class: 'E2', source: 'Run7 in filename' }); expect(measurement.meta_status.run_numbers).toBe('confirmed'); });
  it('refuses confirmation that cannot be re-derived', async () => { const error = await err(() => api.commit({ sample_id: id, groups: [{ key: 'folder:7', confirmed: { run_numbers: { value: [8], class: 'E2', source: 'Run8 in filename' } }, queued: [], files: [file] }] })); expect(error).toMatchObject({ status: 422, code: 'evidence_not_verified' }); expect(state.measurements).toEqual([]); });
  it('queues review items and flags the measurement', async () => { await api.commit({ sample_id: id, groups: [{ key: 'folder:7', confirmed, queued: [{ field: 'temperature_c', candidate_value: 300, reason: 'conflict', evidence_seen: { E3: '300C' } }], files: [file] }] }); expect(state.measurements[0].meta.review_needed).toBe(true); expect(state.review_queue[0]).toMatchObject({ entity: 'measurement', field: 'temperature_c' }); });
  it('returns 404 without creating a sample', async () => { const error = await err(() => api.commit({ sample_id: '22222222-2222-4222-8222-222222222222', groups: [{ key: 'folder:7', confirmed, queued: [], files: [file] }] })); expect(error.status).toBe(404); expect(state.measurements).toEqual([]); });
  it('reports an attached sha256 without duplicating it', async () => { state.files.push({ id: 'files-existing', measurement_id: 'measurements-1', sha256: hash }); const result = await api.commit({ sample_id: id, groups: [{ key: 'folder:7', confirmed, queued: [], files: [file] }] }); expect(result.body.measurements[0].uploads[0]).toMatchObject({ file_id: 'files-existing', already_attached: true }); expect(state.files).toHaveLength(1); });
});
