// @ts-nocheck
import { describe, expect, it } from 'vitest';
import { extractFromPath, proposeGroups } from '../api/_lib/evidence.js';

const clarius = 'Dhiren Site@1 Subsite capacitor DC-IV#1 Run4482 04-21-2026.xlsx';
const queued = (result, field) => result.queued.find((item) => item.field === field);

describe('browser upload evidence', () => {
  it('extracts every E2 token with auditable filename sources', () => { const result = extractFromPath(`8x8 Board/${clarius.replace('capacitor', 'capacitor D3 20um 6.5V 10Hz')}`); expect(result.confirmed).toMatchObject({ run_numbers: { value: [4482], class: 'E2' }, measured_on: { value: '2026-04-21', class: 'E2' }, kind: { value: 'dciv', class: 'E2' }, device_address: { value: 'D3', class: 'E2' }, pad_dim_um: { value: 20, class: 'E2' }, sweep_v: { value: 6.5, class: 'E2' }, frequency_khz: { value: 0.01, class: 'E2' } }); expect(result.confirmed.run_numbers.source).toBe('filename token "Run4482"'); });
  it('extracts E3 folder tokens, including RT and Celsius, but not basename tokens', () => { const rt = extractFromPath(`8x8 Board/RT/25um/D3/10 us pulse/${clarius}`); expect(rt.confirmed).toMatchObject({ temperature_c: { value: 25, class: 'E3' }, pad_dim_um: { value: 25, class: 'E3' }, device_address: { value: 'D3', class: 'E3' }, pulse_width_us: { value: 10, class: 'E3' } }); expect(rt.confirmed.temperature_c.source).toBe('folder segment "RT" (4 levels up)'); const heated = extractFromPath(`8_4 HEATED Write disturb 8x8/300C/${clarius}`); expect(heated.confirmed.temperature_c).toMatchObject({ value: 300, class: 'E3' }); expect(extractFromPath('8x8 Board/300C Run1.xlsx').confirmed.temperature_c).toBeUndefined(); });
  it('writes agreement once with the stronger E2 claim and queues disagreement with both claims', () => { const agreed = extractFromPath(`8x8 Board/20um/${clarius.replace('capacitor', 'capacitor 20um')}`); expect(agreed.confirmed.pad_dim_um).toMatchObject({ value: 20, class: 'E2' }); const conflict = extractFromPath(`8x8 Board/25um/${clarius.replace('capacitor', 'capacitor 20um')}`); expect(conflict.confirmed.pad_dim_um).toBeUndefined(); expect(queued(conflict, 'pad_dim_um')).toMatchObject({ candidate_value: [20, 25] }); expect(queued(conflict, 'pad_dim_um').evidence_seen.map((item) => item.class)).toEqual(['E2', 'E3']); });
  it('queues ambiguous device addresses and never confirms people from paths', () => { const result = extractFromPath(`7_24 D2P2 8x8 samples/Dhiren/${clarius}`); expect(result.confirmed.device_address).toBeUndefined(); expect(queued(result, 'device_address')).toMatchObject({ candidate_value: ['D2', 'P2'] }); expect(result.confirmed.measured_by).toBeUndefined(); });
  it('proposes one group per folder and run number', () => { const groups = proposeGroups([{ path: `8x8 Board/${clarius}` }, { path: `8x8 Board/plot DC-IV_Run4482.png` }, { path: `8x8 Board/Run4483.csv` }, { path: '8_4 HEATED Write disturb 8x8/unlabelled.csv' }]); expect(groups.map(({ folder, run_number }) => [folder, run_number])).toEqual([['8x8 Board', 4482], ['8x8 Board', 4483], ['8_4 HEATED Write disturb 8x8', null]]); expect(groups[0].files).toHaveLength(2); expect(groups[0].confirmed.run_numbers.value).toEqual([4482]); });
});
