insert into vault.field_definitions (entity,key,label,help,type,options_list_key,unit,required,sort_order,group_name,column_name,show_in_table,min,max) values
  ('sample','sample_id','Sample ID','Unique human-readable sample identifier.','text',null,null,true,10,'Identity','sample_id',true,null,null),
  ('sample','label','Label','Descriptive label for the sample.','text',null,null,false,20,'Identity','label',true,null,null),
  ('sample','family','Family','Sample family or campaign name.','text',null,null,false,30,'Identity','family',true,null,null),
  ('sample','owner','Owner','Person responsible for this sample.','person','people',null,false,40,'Identity','owner',false,null,null),
  ('sample','stack','Device stack','Bottom-up layers comprising the device stack.','layer_stack','materials',null,false,50,'Stack','stack',false,null,null),
  ('sample','substrate','Substrate','Substrate material used for the sample.','select','substrates',null,false,60,'Stack','substrate',true,null,null),
  ('sample','substrate_size','Substrate size','Physical substrate form factor.','select','substrate_sizes',null,false,70,'Stack','substrate_size',false,null,null),
  ('sample','fab_location','Fabricated at','Location where the sample was fabricated.','select','locations',null,false,80,'Fabrication','fab_location',true,null,null),
  ('sample','fabricated_by','Fabricated by','Person who fabricated the sample.','person','people',null,false,90,'Fabrication','fabricated_by',false,null,null),
  ('sample','fabricated_on','Fabricated on','Date the sample was fabricated.','date',null,null,false,100,'Fabrication','fabricated_on',true,null,null),
  ('sample','notes','Notes','Free-form notes about the sample.','longtext',null,null,false,200,'Notes','notes',false,null,null),
  ('measurement','measured_on','Measured on','Date the measurement was performed.','date',null,null,true,10,'Session','measured_on',true,null,null),
  ('measurement','kind','Measurement kind','Category of measurement performed.','select','measurement_kinds',null,false,20,'Session','kind',true,null,null),
  ('measurement','measured_by','Measured by','Person who performed the measurement.','person','people',null,false,30,'Session','measured_by',true,null,null),
  ('measurement','instrument','Instrument (Keithley)','Instrument used for this measurement.','select','instruments',null,false,40,'Session','instrument',true,null,null),
  ('measurement','probe_station','Probe station','Probe station used for this measurement.','select','probe_stations',null,false,50,'Session','probe_station',false,null,null),
  ('measurement','temperature_c','Temperature','Chuck temperature during measurement.','number',null,'C',false,60,'Conditions','temperature_c',true,null,null),
  ('measurement','device_address','Device / address','Device identifier or probe address.','text',null,null,false,70,'Conditions','device_address',true,null,null),
  ('measurement','run_numbers','Keithley run numbers','JSON array of integers, e.g. [4482].','json',null,null,false,80,'Conditions','run_numbers',false,null,null),
  ('measurement','pad_shape','Pad shape','Shape of the measured pad.','select','pad_shapes',null,false,90,'Pad geometry','pad_shape',false,null,null),
  ('measurement','pad_dim_um','Pad diameter / edge','Pad diameter for circles or edge length for squares.','number',null,'um',false,100,'Pad geometry','pad_dim_um',true,null,null),
  ('measurement','pad_area_override','Pad area override','Explicit pad area overriding the calculated area.','number',null,'um2',false,110,'Pad geometry','pad_area_override',false,null,null),
  ('measurement','sweep_v','Sweep amplitude','Maximum sweep amplitude.','number',null,'V',false,120,'Sweep',null,false,0,200),
  ('measurement','frequency_khz','Frequency','Measurement frequency.','number',null,'kHz',false,130,'Sweep',null,false,0,null),
  ('measurement','notes','Notes','Free-form notes about the measurement.','longtext',null,null,false,200,'Notes','notes',false,null,null),
  ('file','kind','File kind','Category assigned to the uploaded file.','select','file_kinds',null,false,10,'File','kind',true,null,null)
on conflict (entity, key) do nothing;
