import { useEffect, useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useSearchParams } from 'react-router-dom'
import { Select, Spinner } from '../../components/ui'
import { FilterBar, filtersFromSearchParams, filtersToSearchParams, useFieldDefs, type FilterValue } from '../../fields'
import { cohortCorrelation, cohortSummary, getCohortKeys } from '../../lib/cohorts'
import { CohortChart } from '../cohorts/CohortChart'
import { CorrelationChart } from '../cohorts/CorrelationChart'

export default function CohortExplorer(){const [params,setParams]=useSearchParams(),fields=useFieldDefs('measurement');const keys=useQuery({queryKey:['cohort-keys'],staleTime:60000,queryFn:getCohortKeys});const filters=useMemo(()=>filtersFromSearchParams(params,fields.defs),[params,fields.defs]);const metric=keys.data?.metrics.find(item=>item.metric===params.get('metric'))??keys.data?.metrics[0];const groupKey=keys.data?.group_keys.find(item=>item.key===params.get('group_by'))??keys.data?.group_keys[0];const extractorVersion=params.get('extractor_version');
  // Defaults belong in the URL too; otherwise two identical-looking explorers can run different definitions after a registry change.
  useEffect(()=>{if(!metric||!groupKey||params.get('metric')===metric.metric&&params.get('group_by')===groupKey.key)return;const next=new URLSearchParams(params);next.set('metric',metric.metric);next.set('group_by',groupKey.key);setParams(next,{replace:true})},[groupKey,metric,params,setParams]);
  const result=useQuery({queryKey:['cohort-summary',filters,metric?.metric,groupKey?.key,extractorVersion],enabled:!fields.isLoading&&Boolean(metric&&groupKey),queryFn:()=>cohortSummary({predicate:filters,metric:metric!.metric,group_by:groupKey!.key,...(extractorVersion?{extractor_version:extractorVersion}:{})})});
  // The correlation runs ONLY for a continuous grouping key, and the guard is `enabled` rather
  // than a hidden panel: asking for a fit against "Fab location" is a 422 from the API, and
  // firing it just to discard the error would put a red message under a chart nobody asked for.
  const correlation=useQuery({queryKey:['cohort-correlation',filters,metric?.metric,groupKey?.key,extractorVersion],enabled:!fields.isLoading&&Boolean(metric&&groupKey)&&groupKey?.value_kind==='continuous',queryFn:()=>cohortCorrelation({predicate:filters,metric:metric!.metric,group_by:groupKey!.key,...(extractorVersion?{extractor_version:extractorVersion}:{})})});
  const update=(nextFilters:Record<string,FilterValue>,nextMetric=metric?.metric,nextGroup=groupKey?.key)=>{const next=filtersToSearchParams(nextFilters);if(nextMetric)next.set('metric',nextMetric);if(nextGroup)next.set('group_by',nextGroup);if(extractorVersion)next.set('extractor_version',extractorVersion);setParams(next,{replace:true})};
  if(fields.isLoading||keys.isLoading)return <Spinner/>;if(fields.error||keys.error)return <p className="text-[#B3261E]">{(fields.error??keys.error)?.message}</p>;if(!metric||!groupKey)return <section className="rounded-lg border border-border-subtle bg-white p-6"><h1 className="text-xl font-semibold">Cohort explorer</h1><p className="mt-2 text-sm text-agni-slate">No cohort metrics or grouping keys are registered. Add them through a database migration before exploring cohorts.</p></section>;
  const total=result.data?.total_members??0,noMetric=result.data?.groups.reduce((sum,item)=>sum+item.n_no_metric_row,0)??0;
  return <div className="space-y-4"><header><h1 className="text-xl font-semibold">Cohort explorer</h1><p className="mt-1 text-sm text-agni-slate">Compare computed device metrics without hiding missing results or uncertain grouping data.</p></header><section className="space-y-4 rounded-lg border border-border-subtle bg-white p-4"><div className="grid gap-3 sm:grid-cols-2"><Select label="Metric" value={metric.metric} options={keys.data!.metrics.map(item=>({value:item.metric,label:item.unit?`${item.label} (${item.unit})`:item.label}))} onChange={event=>update(filters,event.target.value,groupKey.key)}/><Select label="Group by" value={groupKey.key} options={keys.data!.group_keys.map(item=>({value:item.key,label:item.unit?`${item.label} (${item.unit})`:item.label}))} onChange={event=>update(filters,metric.metric,event.target.value)}/></div>{metric.notes&&<p className="text-xs text-agni-slate">{metric.notes}</p>}{groupKey.notes&&<p className="text-xs text-agni-slate">{groupKey.notes}</p>}<FilterBar defs={fields.defs} lists={fields.lists} value={filters} onChange={next=>update(next)}/></section>{result.isLoading?<div className="flex justify-center rounded-lg border border-border-subtle bg-white p-8"><Spinner/></div>:result.error?<p className="text-[#B3261E]">{result.error.message}</p>:total===0?<section className="rounded-lg border border-border-subtle bg-white p-6"><h2 className="font-semibold">No measurements match this predicate</h2><p className="mt-2 text-sm text-agni-slate">Widen or clear the filters to include measurements.</p></section>:<>{noMetric===total&&<section className="rounded-lg border border-border-subtle bg-white p-6"><h2 className="font-semibold">No matched measurement has this metric computed yet</h2><p className="mt-2 text-sm text-agni-slate">Run the metric extractor for these {total.toLocaleString()} measurements, or choose another metric. The result ledger remains below so every excluded member and grouping-key provenance bucket is visible.</p></section>}{groupKey.value_kind==='continuous'&&(correlation.isLoading?<div className="flex justify-center rounded-lg border border-border-subtle bg-white p-8"><Spinner/></div>:correlation.error?<p className="text-[#B3261E]">{correlation.error.message}</p>:correlation.data?<CorrelationChart result={correlation.data} metric={metric} groupKey={groupKey}/>:null)}<CohortChart groups={result.data!.groups} metric={metric} groupKey={groupKey}/></>}</div>}

export { CohortExplorer }
