import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { Badge, Spinner } from '../../components/ui'
import { TRACE_COLORS } from '../../plot/panelData'
import { aliasSummary, getDevice, groupHistoryByDay, listDeviceHistory, schemeExplanation, type DeviceHistoryEvent } from '../../lib/devices'

const formatTime=(value:string|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Time not recorded'

function MeasurementEvent({event}:{event:Extract<DeviceHistoryEvent,{event_kind:'measurement'}>}){return <article className="border-l-4 p-3" style={{borderColor:TRACE_COLORS[0]}}><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">Vault measurement</p><p className="text-sm text-agni-slate">{event.detail ?? 'Kind not recorded'}{event.source?` on ${event.source}`:''}</p></div><time className="text-sm text-agni-slate">{formatTime(event.occurred_at)}</time></div></article>}
function BenchCellEvent({event}:{event:Extract<DeviceHistoryEvent,{event_kind:'bench_cell'}>}){return <article className="border-l-4 p-3" style={{borderColor:TRACE_COLORS[2]}}><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">Bench cell result</p><p className="text-sm text-agni-slate">{event.source ?? 'DUT not recorded'}{event.run_id?` / run ${event.run_id}`:''}{event.detail?` / ${event.detail}`:''}</p></div><time className="text-sm text-agni-slate">{formatTime(event.occurred_at)}</time></div>{event.verdict&&<p className="mt-2 font-mono text-sm">verdict: {event.verdict}</p>}</article>}

export default function DeviceDetail(){
  const { id='' }=useParams();const [from,setFrom]=useState('');const [to,setTo]=useState('');const [kind,setKind]=useState<''|DeviceHistoryEvent['event_kind']>('')
  const detail=useQuery({queryKey:['device',id],enabled:Boolean(id),queryFn:()=>getDevice(id)})
  const history=useQuery({queryKey:['device-history',id,from,to,kind],enabled:Boolean(id),queryFn:()=>listDeviceHistory(id,{from:from||undefined,to:to||undefined,event_kind:kind||undefined,limit:500})})
  useEffect(()=>{if(detail.data?.device)document.title=`${detail.data.device.device_address} · Device · Agni Data Vault`},[detail.data])
  if(detail.isLoading)return <Spinner />
  if(detail.error)return <p className="text-[#B3261E]">{detail.error.message}</p>
  const result=detail.data;if(!result)return <section className="space-y-3"><h1 className="text-xl font-semibold">Device not found</h1><Link className="text-agni-orange underline" to="/devices">Back to devices</Link></section>
  const {device,aliases,counts}=result;const grouped=groupHistoryByDay(history.data?.items??[]);const rangeSelected=Boolean(from||to);const knownEvents=counts.measurements+counts.bench_cells
  return <div className="space-y-6"><header className="space-y-3"><Link className="text-sm text-agni-orange underline" to="/devices">Back to devices</Link><div><p className="font-mono text-xs text-agni-slate">{device.sample_id}</p><h1 className="font-mono text-2xl font-semibold">{device.device_address}</h1><div className="mt-2"><Badge tone={device.address_scheme==='bench_grid'?'blue':'gray'}>{device.address_scheme}</Badge></div></div></header>
    <section className="rounded-lg border border-border-subtle bg-white p-4"><h2 className="font-semibold">Address scheme</h2><p className="mt-2 text-sm text-agni-slate">{schemeExplanation(device.address_scheme,device.grid_row,device.grid_col)}</p>{device.notes&&<p className="mt-3 text-sm"><span className="font-medium">Notes: </span>{device.notes}</p>}</section>
    <section className="rounded-lg border border-border-subtle bg-white p-4"><h2 className="font-semibold">Confirmed aliases</h2><p className="mt-1 text-sm text-agni-slate">Aliases are the human-confirmed statements that join addresses into this device history.</p>{aliases.length?<ul className="mt-3 space-y-2">{aliases.map(alias=><li key={alias.id} className="rounded border border-border-subtle p-3 text-sm">{aliasSummary(alias)}</li>)}</ul>:<p className="mt-3 text-sm text-agni-slate">No aliases have been confirmed. This history contains only this device’s own address scheme.</p>}</section>
    <section className="space-y-3"><div><h2 className="text-lg font-semibold">History</h2><p className="text-sm text-agni-slate">{counts.measurements} vault measurement(s), {counts.bench_cells} bench cell event(s). Events are ordered oldest first.</p></div><div className="flex flex-wrap items-end gap-3 rounded-lg border border-border-subtle bg-white p-3"><label className="text-sm">From<input className="mt-1 block rounded border border-border-subtle p-1" type="date" value={from} onChange={event=>setFrom(event.target.value)} /></label><label className="text-sm">To<input className="mt-1 block rounded border border-border-subtle p-1" type="date" value={to} onChange={event=>setTo(event.target.value)} /></label><label className="text-sm">Event type<select className="mt-1 block rounded border border-border-subtle p-1" value={kind} onChange={event=>setKind(event.target.value as ''|DeviceHistoryEvent['event_kind'])}><option value="">All events</option><option value="measurement">Vault measurements</option><option value="bench_cell">Bench cell results</option></select></label></div>{history.isLoading?<Spinner />:history.error?<p className="text-[#B3261E]">{history.error.message}</p>:!grouped.length?<div className="rounded-lg border border-border-subtle bg-white p-6"><p className="font-medium">{rangeSelected&&knownEvents?'No events in the selected range':'No events yet'}</p><p className="mt-1 text-sm text-agni-slate">{rangeSelected&&knownEvents?'This device has recorded events, but none occurred within the selected dates.':'No vault measurement or bench cell result has been recorded for this device.'}</p></div>:<div className="space-y-4">{grouped.map(group=><section key={group.day}><h3 className="mb-2 font-mono text-sm text-agni-slate">{group.day}</h3><div className="space-y-2">{group.items.map(event=>event.event_kind==='measurement'?<MeasurementEvent key={`${event.event_kind}-${event.event_id}`} event={event} />:<BenchCellEvent key={`${event.event_kind}-${event.event_id}`} event={event} />)}</div></section>)}</div>}</section>
  </div>
}
