import { useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useReactTable, getCoreRowModel, type ColumnDef } from '@tanstack/react-table'
import { ArrowDown, ArrowUp, Pencil, Plus } from 'lucide-react'
import { getFieldDefs, getOptionLists, upsertFieldDef } from '../lib/api'
import { Badge, Button, Modal, Spinner, Table } from '../components/ui'
import type { Entity, FieldDef } from '../lib/types'
import { useInvalidateFieldDefs } from '../fields/useFieldDefs'
import { FieldDefForm } from './admin/FieldDefForm'
import { nextSortOrder } from './admin/adminValidation'

const entities: Entity[] = ['sample', 'measurement', 'file']
export default function AdminFields() {
  const [entity, setEntity] = useState<Entity>('sample'); const [retired, setRetired] = useState(false); const [editing, setEditing] = useState<FieldDef | undefined>(); const [open, setOpen] = useState(false)
  const queryClient = useQueryClient(); const invalidateDefs = useInvalidateFieldDefs()
  const defs = useQuery({ queryKey: ['admin-field-defs', entity], queryFn: () => getFieldDefs(entity, true) })
  const lists = useQuery({ queryKey: ['admin-option-lists'], queryFn: () => getOptionLists(true) })
  const visible = useMemo(() => (defs.data ?? []).filter((def) => retired || def.active).sort((a, b) => a.sort_order - b.sort_order), [defs.data, retired])
  const activeCount = (defs.data ?? []).filter((def) => def.active).length
  async function refresh() { await invalidateDefs(); await queryClient.invalidateQueries({ queryKey: ['admin-field-defs'] }) }
  async function save(def: Partial<FieldDef>) { await upsertFieldDef({ ...def, entity, key: def.key ?? '', sort_order: def.sort_order ?? nextSortOrder(defs.data ?? []) }); await refresh(); setOpen(false) }
  async function toggle(def: FieldDef) { if (def.active && !window.confirm('Retiring this field hides it from new use but keeps all existing values. Continue?')) return; await upsertFieldDef({ id: def.id, entity: def.entity, key: def.key, active: !def.active }); await refresh() }
  async function move(def: FieldDef, direction: -1 | 1) { const index = visible.findIndex((item) => item.id === def.id); const neighbor = visible[index + direction]; if (!neighbor) return; await Promise.all([upsertFieldDef({ id: def.id, entity: def.entity, key: def.key, sort_order: neighbor.sort_order }), upsertFieldDef({ id: neighbor.id, entity: neighbor.entity, key: neighbor.key, sort_order: def.sort_order })]); await refresh() }
  const columns: ColumnDef<FieldDef>[] = [{ accessorKey: 'sort_order', header: 'Order' }, { accessorKey: 'key', header: 'Key', cell: ({ row }) => <code>{row.original.key}</code> }, { accessorKey: 'label', header: 'Label' }, { accessorKey: 'type', header: 'Type', cell: ({ row }) => <span>{row.original.type} {row.original.options_list_key && <Badge tone="blue">{row.original.options_list_key}</Badge>}</span> }, { accessorKey: 'unit', header: 'Unit' }, { accessorKey: 'group_name', header: 'Group' }, { accessorKey: 'required', header: 'Required', cell: ({ row }) => row.original.required ? 'Yes' : '—' }, { accessorKey: 'show_in_table', header: 'Table', cell: ({ row }) => row.original.show_in_table ? 'Yes' : '—' }, { accessorKey: 'filterable', header: 'Filter', cell: ({ row }) => row.original.filterable ? 'Yes' : '—' }, { accessorKey: 'active', header: 'Active', cell: ({ row }) => <Badge tone={row.original.active ? 'green' : 'gray'}>{row.original.active ? 'active' : 'retired'}</Badge> }, { id: 'actions', header: 'Actions', cell: ({ row }) => <div className="flex gap-1"><Button size="sm" variant="ghost" aria-label={`Edit ${row.original.label}`} onClick={() => { setEditing(row.original); setOpen(true) }}><Pencil size={15} /></Button><Button size="sm" variant="ghost" aria-label={`${row.original.active ? 'Retire' : 'Restore'} ${row.original.label}`} onClick={() => void toggle(row.original)}>{row.original.active ? 'Retire' : 'Restore'}</Button><Button size="sm" variant="ghost" aria-label={`Move ${row.original.label} up`} disabled={visible[0]?.id === row.original.id} onClick={() => void move(row.original, -1)}><ArrowUp size={15} /></Button><Button size="sm" variant="ghost" aria-label={`Move ${row.original.label} down`} disabled={visible.at(-1)?.id === row.original.id} onClick={() => void move(row.original, 1)}><ArrowDown size={15} /></Button></div> }]
  const table = useReactTable({ data: visible, columns, getCoreRowModel: getCoreRowModel() })
  if (defs.isLoading || lists.isLoading) return <Spinner />
  if (defs.error || lists.error) return <p className="text-red-600">Could not load field definitions: {String(defs.error ?? lists.error)}</p>
  return <section className="space-y-4"><div className="rounded-md border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">Changes here appear immediately in forms, tables, filters, the API schema and the CLI. Retiring a field hides it but keeps existing values.</div><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-1" role="tablist">{entities.map((item) => <Button key={item} size="sm" variant={entity === item ? 'primary' : 'secondary'} role="tab" aria-selected={entity === item} onClick={() => setEntity(item)}>{item[0].toUpperCase() + item.slice(1)}</Button>)}</div><div className="flex items-center gap-3"><span className="text-xs text-gray-500">{activeCount} active</span><label className="text-sm"><input type="checkbox" checked={retired} onChange={(event) => setRetired(event.target.checked)} /> show retired</label><Button onClick={() => { setEditing(undefined); setOpen(true) }}><Plus size={16} />New field</Button></div></div><Table table={table} emptyText="No fields for this entity." /><Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Edit field' : 'New field'}><FieldDefForm entity={entity} initial={editing} existingKeys={(defs.data ?? []).map((def) => def.key)} existingGroups={(defs.data ?? []).flatMap((def) => def.group_name ? [def.group_name] : [])} optionLists={lists.data ?? []} onSave={save} onCancel={() => setOpen(false)} /></Modal></section>
}
