import { useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useReactTable, getCoreRowModel, type ColumnDef } from '@tanstack/react-table'
import { ArrowDown, ArrowUp, Pencil } from 'lucide-react'
import { getOptionLists, upsertOptionValue } from '../lib/api'
import { Badge, Button, Input, Spinner, Table } from '../components/ui'
import type { OptionList, OptionValue } from '../lib/types'
import { useInvalidateFieldDefs } from '../fields/useFieldDefs'
import { nextSortOrder, slugify, validateOptionValue } from './admin/adminValidation'

export default function AdminVocabularies() {
  const [selectedKey, setSelectedKey] = useState<string | null>(null); const [retired, setRetired] = useState(false); const [newLabel, setNewLabel] = useState(''); const [newValue, setNewValue] = useState(''); const [valueTouched, setValueTouched] = useState(false); const [errors, setErrors] = useState<Record<string, string>>({}); const [editing, setEditing] = useState<string | null>(null); const [editLabel, setEditLabel] = useState('')
  const queryClient = useQueryClient(); const invalidateDefs = useInvalidateFieldDefs(); const query = useQuery({ queryKey: ['admin-option-lists'], queryFn: () => getOptionLists(true) })
  const lists = query.data ?? []; const selected: OptionList | undefined = lists.find((list) => list.key === (selectedKey ?? lists[0]?.key)); const values = useMemo(() => (selected?.values ?? []).filter((value) => retired || value.active).sort((a, b) => a.sort_order - b.sort_order), [selected, retired])
  async function refresh() { await invalidateDefs(); await queryClient.invalidateQueries({ queryKey: ['admin-option-lists'] }) }
  async function add() { if (!selected) return; const next = validateOptionValue({ label: newLabel, value: newValue }, selected.values.map((value) => value.value)); setErrors(next); if (Object.keys(next).length) return; await upsertOptionValue({ list_key: selected.key, value: newValue, label: newLabel, sort_order: nextSortOrder(selected.values), active: true, meta: {} }); setNewLabel(''); setNewValue(''); setValueTouched(false); await refresh() }
  async function toggle(value: OptionValue) { if (value.active && !window.confirm('Retiring this option hides it from new selections but keeps it on existing records. Continue?')) return; await upsertOptionValue({ id: value.id, list_key: value.list_key, value: value.value, active: !value.active }); await refresh() }
  async function move(value: OptionValue, direction: -1 | 1) { const index = values.findIndex((item) => item.id === value.id); const neighbor = values[index + direction]; if (!neighbor) return; await Promise.all([upsertOptionValue({ id: value.id, list_key: value.list_key, value: value.value, sort_order: neighbor.sort_order }), upsertOptionValue({ id: neighbor.id, list_key: neighbor.list_key, value: neighbor.value, sort_order: value.sort_order })]); await refresh() }
  async function saveLabel(value: OptionValue) { if (!editLabel.trim()) return; await upsertOptionValue({ id: value.id, list_key: value.list_key, value: value.value, label: editLabel }); setEditing(null); await refresh() }
  const columns: ColumnDef<OptionValue>[] = [{ accessorKey: 'sort_order', header: 'Order' }, { accessorKey: 'value', header: 'Value', cell: ({ row }) => <code>{row.original.value}</code> }, { accessorKey: 'label', header: 'Label', cell: ({ row }) => editing === row.original.id ? <div className="flex gap-1"><input aria-label={`Label for ${row.original.value}`} className="w-36 rounded border px-2 py-1" value={editLabel} onChange={(event) => setEditLabel(event.target.value)} /><Button size="sm" onClick={() => void saveLabel(row.original)}>Save</Button></div> : row.original.label }, { accessorKey: 'active', header: 'Active', cell: ({ row }) => <Badge tone={row.original.active ? 'green' : 'gray'}>{row.original.active ? 'active' : 'retired'}</Badge> }, { id: 'actions', header: 'Actions', cell: ({ row }) => <div className="flex gap-1"><Button size="sm" variant="ghost" aria-label={`Edit ${row.original.label}`} onClick={() => { setEditing(row.original.id); setEditLabel(row.original.label) }}><Pencil size={15} /></Button><Button size="sm" variant="ghost" aria-label={`${row.original.active ? 'Retire' : 'Restore'} ${row.original.label}`} onClick={() => void toggle(row.original)}>{row.original.active ? 'Retire' : 'Restore'}</Button><Button size="sm" variant="ghost" aria-label={`Move ${row.original.label} up`} disabled={values[0]?.id === row.original.id} onClick={() => void move(row.original, -1)}><ArrowUp size={15} /></Button><Button size="sm" variant="ghost" aria-label={`Move ${row.original.label} down`} disabled={values.at(-1)?.id === row.original.id} onClick={() => void move(row.original, 1)}><ArrowDown size={15} /></Button></div> }]
  const table = useReactTable({ data: values, columns, getCoreRowModel: getCoreRowModel() })
  if (query.isLoading) return <Spinner />
  if (query.error) return <p className="text-red-600">Could not load vocabularies: {String(query.error)}</p>
  return <section className="grid gap-6 md:grid-cols-[16rem_1fr]"><aside className="rounded-md border border-gray-200"><h1 className="border-b px-4 py-3 font-semibold">Option lists</h1><ul>{lists.map((list) => <li key={list.key}><button type="button" className={`w-full px-4 py-3 text-left text-sm ${selected?.key === list.key ? 'bg-blue-50 text-blue-800' : 'hover:bg-gray-50'}`} onClick={() => setSelectedKey(list.key)}><code>{list.key}</code><span className="block text-xs text-gray-500">{list.label} · {list.values.filter((value) => value.active).length} active</span></button></li>)}</ul></aside><main className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">{selected?.label ?? 'Option values'}</h1><p className="text-sm text-gray-500">The value is what is stored on records and cannot be renamed, only the label.</p></div><label className="text-sm"><input type="checkbox" checked={retired} onChange={(event) => setRetired(event.target.checked)} /> show retired</label></div>{selected ? <><Table table={table} emptyText="No values in this list." /><div className="rounded-md border border-gray-200 p-4"><h2 className="mb-3 font-medium">Add value</h2><div className="grid gap-3 sm:grid-cols-3"><Input label="Label" value={newLabel} error={errors.label} onChange={(event) => { const label = event.target.value; setNewLabel(label); if (!valueTouched) setNewValue(slugify(label)) }} /><Input label="Value" value={newValue} error={errors.value} onChange={(event) => { setValueTouched(true); setNewValue(event.target.value) }} /><div className="flex items-end"><Button aria-label="Add option value" onClick={() => void add()}>Add value</Button></div></div></div></> : <p className="text-gray-500">No option lists available.</p>}</main></section>
}
