import { useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { getCoreRowModel, useReactTable, type ColumnDef } from '@tanstack/react-table'
import { Badge, Button, Input, Select, Spinner, Table } from '../components/ui'
import { filtersFromSearchParams, filtersToSearchParams, type FilterValue } from '../fields'
import { acceptReviewItem, listReviewQueue, rejectReviewItem } from '../lib/uploads'
import type { FieldDef } from '../lib/types'

type ReviewItem = { id: string; entity: 'sample' | 'measurement'; entity_id: string; field: string; candidate_value: unknown; reason: string; evidence_seen: unknown; status: 'open' | 'accepted' | 'rejected' }
type Evidence = { class?: string; source?: string; value?: unknown; candidate_value?: unknown; label?: string }
const filterDefs = [{ key: 'entity', type: 'text', filterable: true }, { key: 'status', type: 'text', filterable: true }] as FieldDef[]
const displayValue = (value: unknown) => typeof value === 'string' ? value : JSON.stringify(value) ?? String(value)
function evidenceEntries(value: unknown, label?: string): Evidence[] { if (Array.isArray(value)) return value.flatMap((entry) => evidenceEntries(entry, label)); if (value && typeof value === 'object') { const record = value as Record<string, unknown>; if ('class' in record || 'source' in record || 'value' in record || 'candidate_value' in record) return [{ class: typeof record.class === 'string' ? record.class : undefined, source: typeof record.source === 'string' ? record.source : undefined, value: record.value, candidate_value: record.candidate_value, label }]; return Object.entries(record).flatMap(([key, entry]) => evidenceEntries(entry, key)) } return [{ value, label }] }

export default function ReviewQueue() {
  const [params, setParams] = useSearchParams(); const client = useQueryClient(); const [page, setPage] = useState(0); const [edited, setEdited] = useState<Record<string, string>>({}); const [busy, setBusy] = useState<string>(); const [actionError, setActionError] = useState('')
  // Closed sets, declared once. Filters arrive as strings from the URL.
  const ENTITIES = ['sample', 'measurement'] as const
  const STATUSES = ['open', 'accepted', 'rejected'] as const
  const filters = useMemo(() => filtersFromSearchParams(params, filterDefs), [params]); const rawEntity = String(filters.entity ?? ''); const entity = (ENTITIES as readonly string[]).includes(rawEntity) ? rawEntity as (typeof ENTITIES)[number] : undefined; const rawStatus = String(filters.status ?? 'open'); const status = (STATUSES as readonly string[]).includes(rawStatus) ? rawStatus as (typeof STATUSES)[number] : undefined; const limit = 50
  const result = useQuery({ queryKey: ['review-queue', status, entity, page], queryFn: () => listReviewQueue({ status, entity, limit, offset: page * limit }) })
  const updateFilter = (key: 'entity' | 'status', value: string) => { const next: Record<string, FilterValue> = { ...filters, [key]: value }; if (key === 'status' && value === 'open') delete next.status; setParams(filtersToSearchParams(next), { replace: true }); setPage(0) }
  const act = async (id: string, action: () => Promise<unknown>) => { setBusy(id); setActionError(''); try { await action(); await client.invalidateQueries({ queryKey: ['review-queue'] }) } catch (error) { setActionError(error instanceof Error ? error.message : 'Unable to update review item.') } finally { setBusy(undefined) } }
  const acceptEdited = (item: ReviewItem) => { const text = edited[item.id] ?? JSON.stringify(item.candidate_value); let value: unknown; try { value = JSON.parse(text) } catch { setActionError('Edited values must be valid JSON. Put text values in double quotes.'); return } void act(item.id, () => acceptReviewItem(item.id, value)) }
  const columns: ColumnDef<ReviewItem>[] = [
    { id: 'entity', header: 'Entity', cell: ({ row }) => <div className="space-y-1"><Badge tone="blue">{row.original.entity}</Badge><Link className="block max-w-44 truncate font-mono text-xs text-agni-orange underline" title={row.original.entity_id} to={row.original.entity === 'sample' ? `/samples/${row.original.entity_id}` : `/measurements/${row.original.entity_id}`}>{row.original.entity_id}</Link></div> },
    { accessorKey: 'field', header: 'Field', cell: ({ getValue }) => <code className="text-xs">{String(getValue())}</code> },
    { accessorKey: 'candidate_value', header: 'Candidate', cell: ({ getValue }) => <span className="block max-w-56 whitespace-normal font-mono text-xs">{displayValue(getValue())}</span> },
    { accessorKey: 'reason', header: 'Why review is needed', cell: ({ getValue }) => <span className="block min-w-52 max-w-80 whitespace-normal">{String(getValue())}</span> },
    { id: 'evidence_seen', header: 'Evidence seen', cell: ({ row }) => <div className="min-w-60 max-w-96 space-y-2 whitespace-normal">{evidenceEntries(row.original.evidence_seen).map((evidence, index) => <div key={index} className="rounded-md border border-border-subtle bg-surface-2 p-2"><div className="flex flex-wrap items-center gap-2">{evidence.class && <Badge tone="gray">{evidence.class}</Badge>}{evidence.label && <code className="text-xs text-agni-slate">{evidence.label}</code>}<span className="font-mono text-xs">{displayValue('value' in evidence ? evidence.value : evidence.candidate_value)}</span></div>{evidence.source && <p className="mt-1 text-xs text-agni-slate">{evidence.source}</p>}</div>)}</div> },
    { id: 'actions', header: 'Decision', cell: ({ row }) => { const item = row.original; if (item.status !== 'open') return <Badge tone={item.status === 'accepted' ? 'green' : 'gray'}>{item.status}</Badge>; return <div className="min-w-64 space-y-2 whitespace-normal"><Button size="sm" loading={busy === item.id} onClick={() => void act(item.id, () => acceptReviewItem(item.id))}>Accept candidate</Button><div className="flex items-end gap-2"><Input label="Edited value (JSON)" aria-label={`Edited value for ${item.field}`} value={edited[item.id] ?? JSON.stringify(item.candidate_value)} onChange={(event) => setEdited((values) => ({ ...values, [item.id]: event.target.value }))} /><Button size="sm" variant="secondary" disabled={Boolean(busy)} onClick={() => acceptEdited(item)}>Accept edited</Button></div><Button size="sm" variant="danger" disabled={Boolean(busy)} onClick={() => void act(item.id, () => rejectReviewItem(item.id))}>Reject suggestion</Button></div> } },
  ]
  const items = (result.data?.items ?? []) as ReviewItem[]; const table = useReactTable({ data: items, columns, getCoreRowModel: getCoreRowModel() }); const total = result.data?.total ?? 0
  if (result.isLoading) return <Spinner />
  if (result.error) return <p className="text-red-600">{result.error.message}</p>
  return <div className="space-y-5"><header><p className="label-caps text-agni-orange">Evidence decisions</p><h1 className="mt-1 text-xl font-semibold">Review queue</h1><p className="mt-2 max-w-3xl text-sm text-agni-slate">Accept only values supported by the evidence shown. Rejecting a suggestion writes nothing and does not delete any measurement data.</p></header><div className="flex flex-wrap gap-3 rounded-lg border border-border-subtle bg-surface-2 p-4"><Select label="Entity" value={entity} options={[{ value: '', label: 'All entities' }, { value: 'sample', label: 'Samples' }, { value: 'measurement', label: 'Measurements' }]} onChange={(event) => updateFilter('entity', event.target.value)} /><Select label="Status" value={status} options={[{ value: 'open', label: 'Open' }, { value: 'accepted', label: 'Accepted' }, { value: 'rejected', label: 'Rejected' }, { value: '', label: 'All statuses' }]} onChange={(event) => updateFilter('status', event.target.value)} /></div>{actionError && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{actionError}</p>}{items.length === 0 && total === 0 ? <section className="rounded-lg border border-green-200 bg-green-50 px-6 py-10 text-center"><Badge tone="green">Queue clear</Badge><h2 className="mt-3 text-lg font-semibold text-green-950">Nothing is waiting for human review</h2><p className="mt-1 text-sm text-green-800">Every suggestion in this view has been resolved. No action is needed.</p></section> : <><Table table={table} emptyText="No review items match these filters." /><div className="flex items-center justify-between"><span className="text-sm text-agni-slate">{total} item{total === 1 ? '' : 's'}</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={page === 0} onClick={() => setPage((value) => value - 1)}>Previous</Button><Button size="sm" variant="secondary" disabled={(page + 1) * limit >= total} onClick={() => setPage((value) => value + 1)}>Next</Button></div></div></>}</div>
}
