import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { getCoreRowModel, getSortedRowModel, useReactTable, type ColumnDef, type SortingState } from '@tanstack/react-table'
import { Button, Badge, Modal, Spinner, Table } from '../components/ui'
import { EntityForm, FilterBar, columnsFromDefs, filtersFromSearchParams, filtersToSearchParams, useFieldDefs, type FilterValue } from '../fields'
import { createMeasurement, deleteSample, getSample, listFilesForSample, listMeasurements, updateSample } from '../lib/api'
import { groupFilesByMeasurement } from '../lib/fileGroups'
import type { Measurement } from '../lib/types'
import { useAuth } from '../auth/AuthProvider'
import { MetaGrid } from './parts/MetaGrid'
import { StackVisual } from './parts/StackVisual'
import { MeasurementCard } from './parts/MeasurementCard'

type ViewMode = 'table' | 'preview'
type PreviewMode = 'plot' | 'image'
const stored = <T extends string>(key: string, fallback: T): T => { try { return (localStorage.getItem(key) as T | null) ?? fallback } catch { return fallback } }

export default function SampleDetail() {
  const { sampleId = '' } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const { user } = useAuth(); const [search, setSearch] = useSearchParams()
  const [edit, setEdit] = useState(false); const [add, setAdd] = useState(false); const [formError, setFormError] = useState(''); const [sorting, setSorting] = useState<SortingState>([])
  const [view, setView] = useState<ViewMode>(() => stored('vault.sample.view', 'table')); const [previewMode, setPreviewMode] = useState<PreviewMode>(() => stored('vault.sample.previewMode', 'plot')); const [loadAll, setLoadAll] = useState(false)
  const sampleQuery = useQuery({ queryKey: ['sample', sampleId], queryFn: () => getSample(sampleId), enabled: Boolean(sampleId) })
  const sampleFields = useFieldDefs('sample', { includeInactive: true }); const measurementFields = useFieldDefs('measurement')
  const filters = useMemo(() => filtersFromSearchParams(search, measurementFields.defs), [search, measurementFields.defs])
  const measurements = useQuery({ queryKey: ['measurements', sampleQuery.data?.id, filters, measurementFields.defs], enabled: Boolean(sampleQuery.data?.id) && !measurementFields.isLoading, queryFn: () => listMeasurements(sampleQuery.data!.id, { filters, defs: measurementFields.defs, limit: 500 }) })
  const sampleFiles = useQuery({ queryKey: ['sample-files', sampleQuery.data?.id], queryFn: () => listFilesForSample(sampleQuery.data!.id), enabled: view === 'preview' && Boolean(sampleQuery.data?.id) })
  useEffect(() => { try { localStorage.setItem('vault.sample.view', view) } catch { /* unavailable */ } }, [view]); useEffect(() => { try { localStorage.setItem('vault.sample.previewMode', previewMode) } catch { /* unavailable */ } }, [previewMode])
  useEffect(() => { if (sampleQuery.data) document.title = `${sampleQuery.data.sample_id} · Agni Data Vault` }, [sampleQuery.data])
  const rows = useMemo(() => measurements.data?.items ?? [], [measurements.data]); const columns = useMemo<ColumnDef<Measurement>[]>(() => columnsFromDefs<Measurement>(measurementFields.defs, measurementFields.lists), [measurementFields.defs, measurementFields.lists])
  const table = useReactTable({ data: rows, columns, state: { sorting }, onSortingChange: setSorting, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel() })
  const previewRows = useMemo(() => sorting.length ? table.getRowModel().rows.map((row) => row.original) : [...rows].sort((a, b) => (a.temperature_c ?? Infinity) - (b.temperature_c ?? Infinity) || (a.measured_on ?? '').localeCompare(b.measured_on ?? '') || String(a.meta.replicate ?? '').localeCompare(String(b.meta.replicate ?? ''))), [rows, sorting, table])
  const fileGroups = useMemo(() => groupFilesByMeasurement(sampleFiles.data ?? []), [sampleFiles.data])
  if (sampleQuery.isLoading || sampleFields.isLoading) return <Spinner />
  if (sampleQuery.error || sampleFields.error || measurementFields.error || measurements.error) return <p className="text-red-600">{(sampleQuery.error ?? sampleFields.error ?? measurementFields.error ?? measurements.error)?.message}</p>
  const sample = sampleQuery.data
  if (!sample) return <div className="space-y-3"><h1 className="text-xl font-semibold">Sample not found</h1><Link className="text-agni-orange underline" to="/samples">Back to samples</Link></div>
  const facts = { count: rows.length, first: rows.length ? [...rows].sort((a,b) => (a.measured_on ?? '').localeCompare(b.measured_on ?? ''))[0].measured_on : null, last: rows.length ? [...rows].sort((a,b) => (b.measured_on ?? '').localeCompare(a.measured_on ?? ''))[0].measured_on : null }
  const defaultMeasurement: Partial<Measurement> = { measured_on: new Date().toISOString().slice(0, 10), measured_by: (() => { const people = measurementFields.lists.people ?? []; const name = String(user?.user_metadata.full_name ?? user?.email ?? '').toLowerCase(); return people.find((p) => p.label.toLowerCase() === name || p.value.toLowerCase() === name)?.value ?? null })() }
  const saveSample = async (payload: Parameters<typeof updateSample>[1]) => { setFormError(''); try { await updateSample(sample.id, payload, sample.updated_at); await client.invalidateQueries({ queryKey: ['sample', sampleId] }); setEdit(false) } catch (error) { setFormError(error instanceof Error && error.message.includes('conflict') ? 'Conflict: this sample changed. Reload and try again.' : error instanceof Error ? error.message : 'Unable to save sample.') } }
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="font-mono text-2xl font-semibold">{sample.sample_id}</h1>{sample.label && <p className="text-gray-600">{sample.label}</p>}<div className="mt-2 flex gap-2">{sample.family && <Badge tone="blue">{sample.family}</Badge>}{sample.owner && <span className="text-sm text-gray-600">{sample.owner}</span>}</div></div><Button onClick={() => setEdit(true)}>Edit sample</Button></header>
    <div className="grid gap-5 lg:grid-cols-3"><MetaGrid defs={sampleFields.defs} lists={sampleFields.lists} row={sample} onEdit={() => setEdit(true)} /><div className="space-y-2"><StackVisual stack={sample.stack} /><Button variant="secondary" size="sm" onClick={() => setEdit(true)}>Edit stack</Button></div><section className="rounded-lg border border-gray-200 bg-white p-4"><h2 className="font-semibold">Quick facts</h2><dl className="mt-3 space-y-2 text-sm"><div><dt className="text-gray-500">Measurements</dt><dd>{facts.count}</dd></div><div><dt className="text-gray-500">First measured</dt><dd>{facts.first ?? '—'}</dd></div><div><dt className="text-gray-500">Last measured</dt><dd>{facts.last ?? '—'}</dd></div><div><dt className="text-gray-500">Files</dt><dd>Not available in this view</dd></div></dl></section></div>
    <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Measurements</h2><div className="flex items-center gap-2"><div className="rounded-md border border-border-subtle p-0.5"><Button size="sm" variant={view === 'table' ? 'primary' : 'ghost'} onClick={() => setView('table')}>Table</Button><Button size="sm" variant={view === 'preview' ? 'primary' : 'ghost'} onClick={() => setView('preview')}>Preview</Button></div><Button onClick={() => setAdd(true)}>Add measurement</Button></div></div><FilterBar defs={measurementFields.defs} lists={measurementFields.lists} value={filters} onChange={(next: Record<string, FilterValue>) => setSearch(filtersToSearchParams(next), { replace: true })} />
      {view === 'table' ? (measurements.isLoading ? <Spinner /> : <Table table={table} onRowClick={(row) => navigate(`/measurements/${row.id}`)} emptyText="No measurements yet." />) : <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-agni-slate">{previewRows.length} measurements</p><div className="flex items-center gap-2"><div className="rounded-md border border-border-subtle p-0.5"><Button size="sm" variant={previewMode === 'plot' ? 'primary' : 'ghost'} onClick={() => setPreviewMode('plot')}>Plot</Button><Button size="sm" variant={previewMode === 'image' ? 'primary' : 'ghost'} onClick={() => setPreviewMode('image')}>Screenshot</Button></div><span title="Loads every workbook and can use substantial bandwidth."><Button size="sm" variant="secondary" onClick={() => setLoadAll(true)}>Load all charts</Button></span></div></div>{measurements.isLoading || sampleFiles.isLoading ? <Spinner /> : sampleFiles.error ? <p className="text-red-600">{sampleFiles.error.message}</p> : <div className="grid gap-4 [grid-template-columns:repeat(auto-fill,minmax(300px,1fr))]">{previewRows.map((measurement) => <MeasurementCard key={measurement.id} measurement={measurement} files={fileGroups.get(measurement.id) ?? []} sample={sample} mode={previewMode} forceMount={loadAll} onOpen={() => navigate(`/measurements/${measurement.id}`)} />)}</div>}</div>}</section>
    <section className="rounded-lg border border-red-200 bg-red-50 p-4"><h2 className="font-semibold text-red-900">Danger zone</h2><p className="mt-1 text-sm text-red-800">Deleting this sample also deletes its measurements.</p><Button className="mt-3" variant="danger" onClick={async () => { if (window.confirm(`Delete ${sample.sample_id} and its ${facts.count} measurement(s)?`)) { await deleteSample(sample.id); navigate('/samples') } }}>Delete sample</Button></section>
    <Modal open={edit} onClose={() => setEdit(false)} title="Edit sample" size="xl"><>{formError && <p className="mb-3 text-sm text-red-600">{formError}</p>}<EntityForm entity="sample" defs={sampleFields.defs} lists={sampleFields.lists} row={sample} onCancel={() => setEdit(false)} onSubmit={saveSample} /></></Modal>
    <Modal open={add} onClose={() => setAdd(false)} title="Add measurement" size="xl"><EntityForm entity="measurement" defs={measurementFields.defs} lists={measurementFields.lists} row={defaultMeasurement} onCancel={() => setAdd(false)} submitLabel="Create measurement" onSubmit={async (payload) => { const measurement = await createMeasurement(sample.id, payload); await client.invalidateQueries({ queryKey: ['measurements', sample.id] }); navigate(`/measurements/${measurement.id}`) }} /></Modal>
  </div>
}
