import { useLayoutEffect, useRef } from 'react'
import { useQuery } from '@tanstack/react-query'
import uPlot from 'uplot'
import { listBenchAnalysisCells } from '../../lib/bench'

type Metric = 'ec_minus'|'ec_plus'|'onoff'|'vread'
type AnalysisCell = Partial<Record<Metric, number|null>>
type Histogram = { values:number[]; excluded:number; clipped:number; bins:number[]; counts:number[]; median:number; max:number }
const metrics:Array<{key:Metric; label:string; empty:string; unit:string; cap?:number}> = [
  { key:'ec_minus', label:'Ec minus', empty:'no ec_minus resolved for this run', unit:'V' },
  { key:'ec_plus', label:'Ec plus', empty:'no ec_plus resolved for this run', unit:'V' },
  { key:'onoff', label:'On/off ratio', empty:'no onoff resolved for this run', unit:'x', cap:20 },
  { key:'vread', label:'Vread', empty:'no vread resolved for this run', unit:'V' },
]
const median=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);const mid=Math.floor(sorted.length/2);return sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2}
const fmt=(value:number)=>Number.isInteger(value)?String(value):value.toPrecision(3)
function buildHistogram(cells:AnalysisCell[],key:Metric,cap?:number):Histogram{const values=cells.map((cell)=>cell[key]).filter((value):value is number=>typeof value==='number'&&Number.isFinite(value));const max=cap??Math.max(...values);const visible=values.filter((value)=>value<=max);const min=visible.length?Math.min(...visible):0;const high=visible.length?Math.max(...visible):max;const span=high-min||1;const bins=Array.from({length:20},(_,index)=>min+(index+.5)*span/20);const counts=Array.from({length:20},()=>0);for(const value of visible)counts[Math.min(19,Math.floor((value-min)/span*20))]++;return {values,excluded:cells.length-values.length,clipped:values.length-visible.length,bins,counts,median:median(values),max}}
function HistogramChart({histogram,unit}:{histogram:Histogram;unit:string}){const host=useRef<HTMLDivElement>(null);const chart=useRef<uPlot|null>(null);useLayoutEffect(()=>{const element=host.current;if(!element)return;const create=()=>{const width=element.clientWidth;if(!width)return;chart.current?.destroy();chart.current=new uPlot({width,height:190,legend:{show:false},cursor:{show:true},scales:{x:{time:false,auto:false,range:()=>[histogram.bins[0]-(histogram.bins[1]-histogram.bins[0])/2,histogram.max]},y:{auto:false,range:()=>[0,Math.max(1,...histogram.counts)*1.12]}},axes:[{stroke:'#888894',grid:{stroke:'#E8E8EC'},font:'10px IBM Plex Sans',values:(_self,ticks)=>ticks.map(fmt)},{stroke:'#888894',grid:{stroke:'#E8E8EC'},font:'10px IBM Plex Sans',values:(_self,ticks)=>ticks.map(fmt)}],series:[{},{fill:'#1565C0',stroke:'#1565C0',paths:uPlot.paths.bars!({gap:2})}],hooks:{draw:[(self)=>{const x=self.valToPos(Math.min(histogram.median,histogram.max),'x',true);const {top,height}=self.bbox;const ctx=self.ctx;ctx.save();ctx.setLineDash([4,3]);ctx.strokeStyle='#95001A';ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+height);ctx.stroke();ctx.restore()}]}},[histogram.bins,histogram.counts],element)};create();const observer=new ResizeObserver(()=>{const width=element.clientWidth;if(width)chart.current?.setSize({width,height:190})});observer.observe(element);return()=>{observer.disconnect();chart.current?.destroy();chart.current=null}},[histogram]);return <div ref={host} className="h-[190px] w-full" aria-label={`Histogram in ${unit}`}/>} 
export function Histograms({dutId,runId}:{dutId:string;runId:string}){const query=useQuery({queryKey:['bench','analysis','cells',dutId,runId],queryFn:async()=>{const items:AnalysisCell[]=[];for(let offset=0;;offset+=2000){const page=await listBenchAnalysisCells({dutId,runId,limit:2000,offset});items.push(...page.items as AnalysisCell[]);if(items.length>=page.total||!page.items.length)break}return items},enabled:Boolean(dutId&&runId)});return <section className="space-y-3"><div><h2 className="text-lg">Cell analysis distributions</h2><p className="text-sm text-agni-slate">Null values are excluded from every distribution.</p></div><div className="grid gap-4 xl:grid-cols-2">{metrics.map((metric)=>{const histogram=query.data?buildHistogram(query.data,metric.key,metric.cap):null;return <section key={metric.key} className="rounded-lg border border-border-subtle bg-white p-4 shadow-card"><div className="mb-2 flex flex-wrap items-baseline justify-between gap-x-3"><h3 className="text-base text-agni-ink">{metric.label}</h3>{histogram&&<span className="num text-xs text-agni-slate">n = {histogram.values.length} · excluded = {histogram.excluded}</span>}</div>{query.isLoading?<p className="min-h-[190px] text-sm text-agni-slate">Loading analysis cells.</p>:query.error?<p className="min-h-[190px] text-sm text-[#B3261E]">Could not load {metric.key}: {query.error.message}</p>:!histogram?.values.length?<p className="min-h-[190px] text-sm text-agni-slate">{metric.empty}</p>:<><HistogramChart histogram={histogram} unit={metric.unit}/><div className="mt-2 flex flex-wrap gap-x-4 text-xs text-agni-slate"><span className="num">median {fmt(histogram.median)} {metric.unit}</span>{histogram.clipped>0&&<span>{histogram.clipped} {histogram.clipped===1?'cell':'cells'} above {histogram.max}{metric.unit} are off-scale, not dropped.</span>}</div></>}</section>})}</div></section>}
