import { useEffect, useRef, useState } from 'react'
import { Button } from '../../components/ui'

export type UploadInstruction = { path: string; file_id: string; upload_url?: string; sha256: string; file: File; duplicate?: boolean }
type QueueState = 'pending'|'uploading'|'done'|'duplicate'|'error'
type QueueItem = UploadInstruction & { state: QueueState; pct: number; message?: string; attempts: number }
type StoredItem = QueueItem
const databaseName = 'agni-data-vault'; const storeName = 'folder-upload-queue'
const displayBytes = (value: number) => value >= 1024 * 1024 ? `${(value / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(value / 1024))} KB`
const openDatabase = () => new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(databaseName, 1); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains(storeName)) request.result.createObjectStore(storeName, { keyPath: 'sha256' }) }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) })
async function loadStored() { try { const db = await openDatabase(); return await new Promise<StoredItem[]>((resolve, reject) => { const request = db.transaction(storeName).objectStore(storeName).getAll(); request.onsuccess = () => resolve(request.result as StoredItem[]); request.onerror = () => reject(request.error) }) } catch { return null } }
async function saveStored(item: QueueItem) { try { const db = await openDatabase(); await new Promise<void>((resolve, reject) => { const request = db.transaction(storeName, 'readwrite').objectStore(storeName).put(item); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error) }) } catch { void 0 } }
async function removeStored(sha256: string) { try { const db = await openDatabase(); await new Promise<void>((resolve, reject) => { const request = db.transaction(storeName, 'readwrite').objectStore(storeName).delete(sha256); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error) }) } catch { void 0 } }
const sleep = (ms: number) => new Promise((resolve) => window.setTimeout(resolve, ms))
function putFile(item: QueueItem, onProgress: (pct: number) => void) { return new Promise<void>((resolve, reject) => { if (!item.upload_url) { resolve(); return } const request = new XMLHttpRequest(); request.open('PUT', item.upload_url); request.withCredentials = true; request.setRequestHeader('Content-Type', item.file.type || 'application/octet-stream'); request.upload.onprogress = (event) => { if (event.lengthComputable) onProgress(Math.round(event.loaded / event.total * 100)) }; request.onload = () => request.status >= 200 && request.status < 300 ? resolve() : reject(Object.assign(new Error(`Upload failed (${request.status})`), { status: request.status })); request.onerror = () => reject(Object.assign(new Error('Network error while uploading'), { status: 0 })); request.ontimeout = () => reject(Object.assign(new Error('Upload timed out'), { status: 408 })); request.send(item.file) }) }

export function UploadQueue({ uploads }: { uploads: UploadInstruction[] }) {
  const [items, setItems] = useState<QueueItem[]>([]); const [loaded, setLoaded] = useState(false); const running = useRef(false)
  useEffect(() => { void loadStored().then((stored) => { if (stored?.length) setItems(stored.map((item) => ({ ...item, state: item.state === 'uploading' ? 'pending' : item.state }))); setLoaded(true) }) }, [])
  useEffect(() => { if (!uploads.length) return; setItems((current) => { const known = new Set(current.map((item) => item.sha256)); const added: QueueItem[] = uploads.filter((item) => !known.has(item.sha256)).map((item) => ({ ...item, state: item.duplicate ? 'duplicate' : 'pending', pct: item.duplicate ? 100 : 0, attempts: 0 })); return [...current, ...added] }) }, [uploads])
  useEffect(() => { for (const item of items) { if (item.state === 'done' || item.state === 'duplicate') void removeStored(item.sha256); else void saveStored(item) } }, [items])
  const update = (sha256: string, patch: Partial<QueueItem>) => setItems((current) => current.map((item) => item.sha256 === sha256 ? { ...item, ...patch } : item))
  const transfer = async (item: QueueItem) => { for (let attempt = item.attempts; attempt < 4; attempt++) { update(item.sha256, { state: 'uploading', attempts: attempt + 1, pct: item.pct, message: undefined }); try { await putFile(item, (pct) => update(item.sha256, { pct })); update(item.sha256, { state: 'done', pct: 100 }); return } catch (reason: unknown) { const status = typeof reason === 'object' && reason !== null && 'status' in reason ? Number(reason.status) : 0; const message = reason instanceof Error ? reason.message : String(reason); if (status >= 400 && status < 500 && status !== 408 && status !== 429 || attempt === 3) { update(item.sha256, { state: 'error', message }); return } await sleep(1000 * 2 ** attempt) } } }
  const start = async () => { if (running.current) return; running.current = true; const pending = items.filter((item) => item.state === 'pending' || item.state === 'error').map((item) => item.state === 'error' ? { ...item, attempts: 0, pct: 0 } : item); let next = 0; await Promise.all(Array.from({ length: 3 }, async () => { while (next < pending.length) { const item = pending[next++]; await transfer(item) } })); running.current = false }
  if (!loaded) return null
  if (!items.length) return <section className="rounded-lg border border-dashed border-border-subtle bg-white p-5 text-sm text-agni-slate">No transfers are queued. Commit an analysed folder to begin uploading.</section>
  const pending = items.some((item) => item.state === 'pending' || item.state === 'error')
  return <section className="space-y-3 rounded-lg border border-border-subtle bg-white p-4 shadow-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Transfer queue</h2><p className="text-sm text-agni-slate">Three files transfer at a time. Interrupted uploads can be resumed safely.</p></div><Button type="button" onClick={() => void start()} disabled={!pending}>{items.some((item) => item.state === 'error') ? 'Retry failed transfers' : 'Start transfers'}</Button></div><ul className="divide-y divide-border-subtle">{items.map((item) => <li key={item.sha256} className="py-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium text-agni-ink">{item.path}</span><span className={item.state === 'error' ? 'text-[#B3261E]' : item.state === 'duplicate' ? 'text-agni-slate' : item.state === 'done' ? 'text-green-700' : 'text-agni-slate'}>{item.state === 'uploading' ? `uploading ${item.pct}%` : item.state === 'duplicate' ? 'already uploaded' : item.state === 'done' ? 'uploaded' : item.state === 'error' ? `failed: ${item.message}` : 'waiting'}</span></div><div className="mt-1 flex items-center gap-3 text-xs text-agni-slate"><span>{displayBytes(item.file.size)}</span>{item.state === 'uploading' && <div className="h-1.5 w-32 overflow-hidden rounded bg-surface-2"><div className="h-full bg-agni-orange" style={{ width: `${item.pct}%` }} /></div>}</div></li>)}</ul></section>
}
