import { useState, type FormEvent } from 'react'
import { Navigate, useLocation } from 'react-router-dom'
import { Button, Input } from '../components/ui'
import { useAuth } from './AuthProvider'
export default function Login() {
  const { session, signInWithOtp, verifyOtp } = useAuth(); const location = useLocation(); const from = (location.state as { from?: string } | null)?.from
  const [email, setEmail] = useState(''); const [token, setToken] = useState(''); const [sent, setSent] = useState(false); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(false)
  if (session) return <Navigate to={from ?? '/'} replace />
  const friendlyError = (message: string) => message.includes('email_not_allowlisted') || message.includes('Database error saving new user') ? 'This email is not on the allowlist. Ask an admin to add it.' : message.includes('Signups not allowed') ? 'Sign-ups are disabled in the Supabase project settings; enable them — the allowlist trigger still blocks unknown emails.' : message
  async function send(event: FormEvent) { event.preventDefault(); setLoading(true); setError(undefined); const result = await signInWithOtp(email); setLoading(false); if (result.error) setError(friendlyError(result.error)); else setSent(true) }
  async function verify(event: FormEvent) { event.preventDefault(); setLoading(true); setError(undefined); const result = await verifyOtp(email, token); setLoading(false); if (result.error) setError(result.error) }
  return <main className="flex min-h-screen items-center justify-center bg-white p-4"><section className="w-full max-w-md rounded-lg border border-border-subtle bg-white p-6 shadow-card"><img src="/agni-logo.png" alt="Agni" className="w-40" /><h1 className="mt-6 text-2xl">Sign in</h1><p className="mt-2 text-sm text-agni-slate">Sign in with your approved work email.</p><form className="mt-6 space-y-4" onSubmit={send}><Input label="Email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="email" /><Button className="w-full" type="submit" loading={loading}>Send magic link</Button></form>{sent && <form className="mt-6 space-y-4 border-t border-border-subtle pt-5" onSubmit={verify}><p className="text-sm font-medium text-[#1B7F3B]">Check your email. You can also enter the 6-digit code below.</p><Input label="Verification code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={token} onChange={(event) => setToken(event.target.value.replace(/\D/g, ''))} /><Button className="w-full" type="submit" loading={loading} disabled={token.length !== 6}>Verify code</Button></form>}{error && <p role="alert" className="mt-4 text-sm text-[#B3261E]">{error}</p>}</section></main>
}
