import { useEffect, useRef, useState } from 'react'
import clsx from 'clsx'
import { Badge } from './Badge'
export interface ComboboxProps { options: { value: string; label: string; inactive?: boolean }[]; value: string | string[] | null; onChange: (value: string | string[] | null) => void; multiple?: boolean; placeholder?: string; allowClear?: boolean; label?: string; error?: string }
export function Combobox({ options, value, onChange, multiple = false, placeholder = 'Select…', allowClear = false, label, error }: ComboboxProps) {
  const root = useRef<HTMLDivElement>(null); const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const [highlight, setHighlight] = useState(0)
  const selected = Array.isArray(value) ? value : value ? [value] : []
  const visible = options.filter((option) => (!option.inactive || selected.includes(option.value)) && option.label.toLowerCase().includes(query.toLowerCase()))
  useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [])
  function choose(next: string) { if (multiple) onChange(selected.includes(next) ? selected.filter((item) => item !== next) : [...selected, next]); else { onChange(next); setOpen(false); setQuery('') } }
  function keyDown(event: React.KeyboardEvent<HTMLInputElement>) { if (event.key === 'ArrowDown') { event.preventDefault(); setOpen(true); setHighlight((index) => Math.min(index + 1, visible.length - 1)) } else if (event.key === 'ArrowUp') { event.preventDefault(); setHighlight((index) => Math.max(index - 1, 0)) } else if (event.key === 'Enter' && open && visible[highlight]) { event.preventDefault(); choose(visible[highlight].value) } else if (event.key === 'Escape') setOpen(false) }
  const selectedOptions = options.filter((option) => selected.includes(option.value))
  return <div ref={root} className="relative"><label className="block text-xs font-medium text-agni-ink">{label && <span className="mb-1 block">{label}</span>}<div className={clsx('flex min-h-10 flex-wrap items-center gap-1 rounded-md border bg-white px-2 py-1 focus-within:border-agni-orange', error ? 'border-[#B3261E]' : 'border-border-subtle')}>{multiple && selectedOptions.map((option) => <span key={option.value} className="inline-flex items-center gap-1 rounded-full border border-border-subtle bg-agni-orange-tint px-2 py-0.5 text-xs text-agni-orange">{option.label}<button type="button" aria-label={'Remove ' + option.label} onClick={() => choose(option.value)}>×</button></span>)}<input className="min-w-24 flex-1 border-0 bg-transparent p-1 text-sm outline-none" value={query} placeholder={!multiple && selectedOptions[0] ? selectedOptions[0].label : placeholder} onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); setOpen(true); setHighlight(0) }} onKeyDown={keyDown} />{allowClear && selected.length > 0 && <button type="button" className="px-1 text-agni-slate" onClick={() => onChange(multiple ? [] : null)}>×</button>}</div></label>{error && <p className="mt-1 text-xs text-[#B3261E]">{error}</p>}{open && <ul className="absolute z-20 mt-1 max-h-56 w-full overflow-auto rounded-lg border border-border-subtle bg-white py-1 shadow-card">{visible.length ? visible.map((option, index) => <li key={option.value}><button type="button" className={clsx('flex w-full items-center justify-between px-3 py-2 text-left text-sm hover:bg-agni-orange-tint', index === highlight && 'bg-agni-orange-tint')} onMouseEnter={() => setHighlight(index)} onClick={() => choose(option.value)}>{option.label}{option.inactive && <Badge tone="gray">retired</Badge>}</button></li>) : <li className="px-3 py-2 text-sm text-agni-slate">No matches.</li>}</ul>}</div>
}
